import React, { useCallback, useEffect } from 'react';
import { Text } from '@mantine/core';
import SectionCard from '~/components/SectionCard';
import ConversationsList from '~/modules/conversations/ConversationsList';
import ConversationDetails from '~/modules/conversations/ConversationDetails';
import type { ConversationsModel } from '~/models/ConversationsModels';
import { useCampaignsStore } from '~/stores/campaignsStore';

interface ConversationsSectionProps {
	campaignId?: number | string;
}

const ConversationsSection: React.FC<ConversationsSectionProps> = ({
	campaignId,
}) => {
	const setRightComponent = useCampaignsStore(
		(state) => state.setRightComponent
	);

	useEffect(() => {
		setRightComponent(null);
		return () => setRightComponent(null);
	}, [campaignId, setRightComponent]);

	const handleConversationClick = useCallback(
		(conversation: ConversationsModel) => {
			setRightComponent(<ConversationDetails id={conversation.id} />);
		},
		[setRightComponent]
	);

	if (!campaignId) {
		return (
			<SectionCard
				title='Conversations'
				description='Review the conversations generated by this campaign.'
			>
				<Text size='sm' c='dimmed'>
					Save the campaign details to start tracking conversations.
				</Text>
			</SectionCard>
		);
	}

	return (
		<SectionCard
			title='Conversations'
			description='Review the conversations generated by this campaign.'
		>
			<ConversationsList
				campaignId={campaignId}
				onConversationClick={handleConversationClick}
			/>
		</SectionCard>
	);
};

export default ConversationsSection;
