/**
 * Seeded Coaching state: rules, sessions, cohorts and the activity feed.
 * Derived from TEAM_PROFILES so the roster stays consistent across sections.
 */
import type {
	CoachingActivityEntry,
	CoachingCohort,
	CoachingRule,
	CoachingSessionRecord,
	RuleCondition,
	RuleScope,
} from '~/models/qa';
import { TEAM_PROFILES } from '~/modules/qa/team/mockData';
import { DIMENSION_TO_AREA } from '~/modules/qa/lms/constants';
import { day, seeded } from '~/modules/qa/lms/mockData';
import { DEFAULT_FOLLOW_UP } from './constants';

const CREATED_AT = '2026-07-01T09:00:00Z';
const UPDATED_AT = '2026-09-01T09:00:00Z';

const emptyScope = (): RuleScope => ({
	agentIds: [],
	supervisorIds: [],
	campaignIds: [],
	linesOfBusiness: [],
	campaignTypes: [],
});

const condition = (partial: Partial<RuleCondition> & Pick<RuleCondition, 'id' | 'metricId'>): RuleCondition => ({
	subItem: null,
	mode: 'THRESHOLD',
	operator: 'LT',
	value: 0,
	value2: null,
	changeDirection: 'DECREASE',
	changePercent: 10,
	consecutiveCount: 3,
	window: 'LAST_14_DAYS',
	windowSize: 10,
	...partial,
});

// ── Rules ─────────────────────────────────────────────────────────────────────

export const COACHING_RULE_SEEDS: CoachingRule[] = [
	{
		id: 'cr-001',
		name: 'Compliance below 85 → certification',
		description:
			'When an agent averages under 85% on compliance over two weeks, assign the disclosures document and the annual certification quiz.',
		status: 'ACTIVE',
		area: 'COMPLIANCE',
		conditions: [
			condition({ id: 'cr-001-c1', metricId: 'COMPLIANCE_OVERALL_SCORE', operator: 'LT', value: 85, window: 'LAST_14_DAYS' }),
		],
		conditionLogic: 'ALL',
		scope: emptyScope(),
		action: {
			kind: 'ASSIGN_CONTENT',
			contentIds: ['lms-c08', 'lms-c11'],
			pathId: null,
			mandatory: true,
			dueInDays: 14,
			requireAcceptance: true,
			scheduleSession: false,
			sessionTopic: 'Mandatory disclosures',
			sessionCoach: 'QA_MANAGER',
			notifySupervisor: true,
		},
		followUp: { ...DEFAULT_FOLLOW_UP },
		cooldownDays: 30,
		stats: { triggeredLast30Days: 6, agentsAffected: 5, improvedRate: 60, lastTriggeredAt: '2026-09-10T08:00:00Z' },
		createdBy: 'Elena Ruiz',
		createdByRole: 'QA_MANAGER',
		createdAt: CREATED_AT,
		updatedAt: UPDATED_AT,
	},
	{
		id: 'cr-002',
		name: 'Negative emotion share above 30% → De-escalation',
		description:
			'When more than 30% of an agent calls carry negative customer emotion over two weeks, assign de-escalation material and book a 1:1.',
		status: 'ACTIVE',
		area: 'SENTIMENT_EMOTION',
		conditions: [
			condition({
				id: 'cr-002-c1',
				metricId: 'NEGATIVE_EMOTION_CALL_SHARE',
				operator: 'GT',
				value: 30,
				window: 'LAST_14_DAYS',
			}),
		],
		conditionLogic: 'ALL',
		scope: { ...emptyScope(), supervisorIds: ['SUP-001'] },
		action: {
			kind: 'ASSIGN_CONTENT',
			contentIds: ['lms-c15', 'lms-c14'],
			pathId: null,
			mandatory: true,
			dueInDays: 10,
			requireAcceptance: true,
			scheduleSession: true,
			sessionTopic: 'Handling frustrated customers',
			sessionCoach: 'SUPERVISOR',
			notifySupervisor: true,
		},
		followUp: { ...DEFAULT_FOLLOW_UP },
		cooldownDays: 21,
		stats: { triggeredLast30Days: 3, agentsAffected: 3, improvedRate: 67, lastTriggeredAt: '2026-09-11T10:30:00Z' },
		createdBy: 'Maria García',
		createdByRole: 'SUPERVISOR',
		createdAt: CREATED_AT,
		updatedAt: UPDATED_AT,
	},
	{
		id: 'cr-003',
		name: '3 consecutive non-critical errors → Needs assessment',
		description:
			'Three calls in a row with a non-critical error assign the discovery-questions document and the practice scenario.',
		status: 'ACTIVE',
		area: 'QUALITY_ASSURANCE',
		conditions: [
			condition({
				id: 'cr-003-c1',
				metricId: 'QA_ENC_COUNT',
				mode: 'CONSECUTIVE',
				operator: 'GTE',
				value: 1,
				consecutiveCount: 3,
				window: 'LAST_N_CALLS',
				windowSize: 10,
			}),
		],
		conditionLogic: 'ALL',
		scope: { ...emptyScope(), supervisorIds: ['SUP-001'] },
		action: {
			kind: 'ASSIGN_CONTENT',
			contentIds: ['lms-c02', 'lms-c06'],
			pathId: null,
			mandatory: true,
			dueInDays: 7,
			requireAcceptance: true,
			scheduleSession: false,
			sessionTopic: 'Needs assessment',
			sessionCoach: 'SUPERVISOR',
			notifySupervisor: false,
		},
		followUp: { ...DEFAULT_FOLLOW_UP },
		cooldownDays: 14,
		stats: { triggeredLast30Days: 2, agentsAffected: 2, improvedRate: 100, lastTriggeredAt: '2026-07-20T09:00:00Z' },
		createdBy: 'Maria García',
		createdByRole: 'SUPERVISOR',
		createdAt: CREATED_AT,
		updatedAt: UPDATED_AT,
	},
	{
		id: 'cr-004',
		name: 'Unhandled objections above 20% → Sales path',
		description: 'Sales agents who leave more than one objection in five unanswered are enrolled in the sales path.',
		status: 'ACTIVE',
		area: 'BUSINESS_INSIGHTS',
		conditions: [
			condition({
				id: 'cr-004-c1',
				metricId: 'BI_UNHANDLED_OBJECTION_RATE',
				operator: 'GT',
				value: 20,
				window: 'LAST_30_DAYS',
			}),
		],
		conditionLogic: 'ALL',
		scope: { ...emptyScope(), linesOfBusiness: ['Sales'] },
		action: {
			kind: 'ASSIGN_PATH',
			contentIds: [],
			pathId: 'path-business',
			mandatory: false,
			dueInDays: 21,
			requireAcceptance: false,
			scheduleSession: false,
			sessionTopic: 'Objection handling',
			sessionCoach: 'SUPERVISOR',
			notifySupervisor: true,
		},
		followUp: { ...DEFAULT_FOLLOW_UP },
		cooldownDays: 45,
		stats: { triggeredLast30Days: 4, agentsAffected: 4, improvedRate: 50, lastTriggeredAt: '2026-09-02T09:00:00Z' },
		createdBy: 'Elena Ruiz',
		createdByRole: 'QA_MANAGER',
		createdAt: CREATED_AT,
		updatedAt: UPDATED_AT,
	},
	{
		id: 'cr-005',
		name: 'Do-Not-Call violation → DNC refresher + QA Manager session',
		description: 'A single do-not-call violation assigns the refresher within three days and books a session with the QA manager.',
		status: 'ACTIVE',
		area: 'COMPLIANCE',
		conditions: [
			condition({
				id: 'cr-005-c1',
				metricId: 'COMPLIANCE_VIOLATION_COUNT',
				subItem: 'noLlamarList',
				operator: 'GTE',
				value: 1,
				window: 'PER_CALL',
			}),
		],
		conditionLogic: 'ALL',
		scope: emptyScope(),
		action: {
			kind: 'ASSIGN_CONTENT',
			contentIds: ['lms-c13'],
			pathId: null,
			mandatory: true,
			dueInDays: 3,
			requireAcceptance: true,
			scheduleSession: true,
			sessionTopic: 'Mandatory disclosures',
			sessionCoach: 'QA_MANAGER',
			notifySupervisor: true,
		},
		followUp: { ...DEFAULT_FOLLOW_UP, checkpointDays: [7, 30] },
		cooldownDays: 7,
		stats: { triggeredLast30Days: 1, agentsAffected: 1, improvedRate: null, lastTriggeredAt: '2026-08-27T15:00:00Z' },
		createdBy: 'Elena Ruiz',
		createdByRole: 'QA_MANAGER',
		createdAt: CREATED_AT,
		updatedAt: UPDATED_AT,
	},
	{
		id: 'cr-006',
		name: 'QA score dropped 10% → QA Essentials',
		description: 'A ten-percent drop in the monthly QA score enrols the agent in the QA Essentials path.',
		status: 'PAUSED',
		area: 'QUALITY_ASSURANCE',
		conditions: [
			condition({
				id: 'cr-006-c1',
				metricId: 'QA_OVERALL_SCORE',
				mode: 'PERCENT_CHANGE',
				changeDirection: 'DECREASE',
				changePercent: 10,
				window: 'LAST_30_DAYS',
			}),
		],
		conditionLogic: 'ALL',
		scope: { ...emptyScope(), supervisorIds: ['SUP-001'] },
		action: {
			kind: 'ASSIGN_PATH',
			contentIds: [],
			pathId: 'path-qa',
			mandatory: true,
			dueInDays: 30,
			requireAcceptance: true,
			scheduleSession: false,
			sessionTopic: 'Needs assessment',
			sessionCoach: 'SUPERVISOR',
			notifySupervisor: true,
		},
		followUp: { ...DEFAULT_FOLLOW_UP },
		cooldownDays: 30,
		stats: { triggeredLast30Days: 0, agentsAffected: 0, improvedRate: null, lastTriggeredAt: null },
		createdBy: 'Maria García',
		createdByRole: 'SUPERVISOR',
		createdAt: CREATED_AT,
		updatedAt: UPDATED_AT,
	},
	{
		id: 'cr-007',
		name: 'Auto-fail → critical errors video',
		description: 'Any auto-failed call assigns the critical-error prevention video within five days.',
		status: 'DRAFT',
		area: 'QUALITY_ASSURANCE',
		conditions: [
			condition({ id: 'cr-007-c1', metricId: 'QA_AUTO_FAIL_COUNT', operator: 'GTE', value: 1, window: 'PER_CALL' }),
		],
		conditionLogic: 'ALL',
		scope: emptyScope(),
		action: {
			kind: 'ASSIGN_CONTENT',
			contentIds: ['lms-c07'],
			pathId: null,
			mandatory: true,
			dueInDays: 5,
			requireAcceptance: true,
			scheduleSession: false,
			sessionTopic: 'Auto-fail prevention',
			sessionCoach: 'SUPERVISOR',
			notifySupervisor: true,
		},
		followUp: { ...DEFAULT_FOLLOW_UP },
		cooldownDays: 14,
		stats: { triggeredLast30Days: 0, agentsAffected: 0, improvedRate: null, lastTriggeredAt: null },
		createdBy: 'Elena Ruiz',
		createdByRole: 'QA_MANAGER',
		createdAt: CREATED_AT,
		updatedAt: UPDATED_AT,
	},
];

// ── Sessions ──────────────────────────────────────────────────────────────────

const STATUS_MAP = {
	scheduled: 'SCHEDULED',
	completed: 'COMPLETED',
	missed: 'MISSED',
} as const;

function buildRosterSessions(): CoachingSessionRecord[] {
	const out: CoachingSessionRecord[] = [];

	for (const profile of Object.values(TEAM_PROFILES)) {
		const rand = seeded(Number(profile.agent.id.replace(/\D/g, '')) * 7331);

		for (const legacy of profile.coaching) {
			const isQaManager = legacy.coachRole === 'QA_MANAGER';
			const status = STATUS_MAP[legacy.status];
			const ack = rand() < 0.7;
			const ackAt = ack ? `${day(legacy.date.slice(0, 10), 1)}T09:00:00Z` : null;
			const done = rand() < 0.5;

			out.push({
				id: legacy.id,
				agentId: profile.agent.id,
				agentName: profile.agent.name,
				coachId: isQaManager ? 'QAM-001' : profile.agent.supervisorId,
				coachName: legacy.coachName,
				coachRole: legacy.coachRole,
				type: 'ONE_ON_ONE',
				date: legacy.date,
				durationMin: 30,
				topic: legacy.topic,
				area: legacy.linkedDimension ? DIMENSION_TO_AREA[legacy.linkedDimension] : null,
				subItem: null,
				evidenceCallIds: status === 'COMPLETED' ? ['call-001'] : [],
				talkingPoints: [
					`Review last week's ${legacy.topic.toLowerCase()} calls`,
					'Agree one behaviour to practise',
				],
				notes: '',
				actionItems:
					status === 'COMPLETED'
						? [
								{
									id: `${legacy.id}-ai1`,
									text: legacy.outcome ?? 'Practise on live calls this week',
									dueDate: legacy.followUpDate ?? day(legacy.date.slice(0, 10), 14),
									done,
									acknowledgedByAgent: ack,
									acknowledgedAt: ackAt,
								},
							]
						: [],
				agentCommitment: { acknowledged: status === 'COMPLETED' ? ack : false, acknowledgedAt: ackAt, comment: null },
				status,
				outcome: legacy.outcome ?? null,
				followUpDate: legacy.followUpDate ?? null,
				linkedAssignmentIds: [],
				ruleId: null,
				cohortId: null,
			});
		}
	}

	return out;
}

const CURATED_SESSIONS: CoachingSessionRecord[] = [
	{
		id: 'coa-a04-rule',
		agentId: 'AGT-004',
		agentName: 'John Smith',
		coachId: 'SUP-001',
		coachName: 'Maria García',
		coachRole: 'SUPERVISOR',
		type: 'ONE_ON_ONE',
		date: '2026-09-16T14:00:00Z',
		durationMin: 30,
		topic: 'Handling frustrated customers',
		area: 'SENTIMENT_EMOTION',
		subItem: 'FRUSTRATION',
		evidenceCallIds: ['call-001', 'call-104'],
		talkingPoints: [
			'Listen to call-104 minute 3: the tone shift',
			'Practise the acknowledge-then-ask opener',
			'Agree the de-escalation phrases to use',
		],
		notes: '',
		actionItems: [],
		agentCommitment: { acknowledged: false, acknowledgedAt: null, comment: null },
		status: 'SCHEDULED',
		outcome: null,
		followUpDate: null,
		linkedAssignmentIds: ['lms-a04-01'],
		ruleId: 'cr-002',
		cohortId: null,
	},
	{
		id: 'coa-a06-1',
		agentId: 'AGT-006',
		agentName: 'David Brown',
		coachId: 'SUP-001',
		coachName: 'Maria García',
		coachRole: 'SUPERVISOR',
		type: 'SIDE_BY_SIDE',
		date: '2026-09-15T09:30:00Z',
		durationMin: 45,
		topic: 'Stress management',
		area: 'SENTIMENT_EMOTION',
		subItem: 'WELLBEING',
		evidenceCallIds: [],
		talkingPoints: ['Listen together to two calls from the busiest hour', 'Agree a micro-break routine'],
		notes: '',
		actionItems: [],
		agentCommitment: { acknowledged: false, acknowledgedAt: null, comment: null },
		status: 'SCHEDULED',
		outcome: null,
		followUpDate: null,
		linkedAssignmentIds: [],
		ruleId: null,
		cohortId: null,
	},
	{
		id: 'coa-a17-1',
		agentId: 'AGT-017',
		agentName: 'Nina Patel',
		coachId: 'QAM-001',
		coachName: 'Elena Ruiz',
		coachRole: 'QA_MANAGER',
		type: 'ONE_ON_ONE',
		date: '2026-09-04T11:00:00Z',
		durationMin: 30,
		topic: 'Mandatory disclosures',
		area: 'COMPLIANCE',
		subItem: 'noLlamarList',
		evidenceCallIds: ['call-001'],
		talkingPoints: ['Walk through the DNC pre-call check', 'Review the flagged call'],
		notes: 'Agent was receptive; the miss came from a rushed queue.',
		actionItems: [
			{
				id: 'coa-a17-1-ai1',
				text: 'Use the pre-call checklist on every outbound call',
				dueDate: '2026-09-11',
				done: true,
				acknowledgedByAgent: true,
				acknowledgedAt: '2026-09-05T08:30:00Z',
			},
			{
				id: 'coa-a17-1-ai2',
				text: 'Self-review two outbound calls and share notes',
				dueDate: '2026-09-18',
				done: false,
				acknowledgedByAgent: false,
				acknowledgedAt: null,
			},
		],
		agentCommitment: { acknowledged: false, acknowledgedAt: null, comment: null },
		status: 'COMPLETED',
		outcome: 'Reviewed the DNC check step; agent will use the pre-call checklist',
		followUpDate: '2026-09-18',
		linkedAssignmentIds: [],
		ruleId: 'cr-005',
		cohortId: null,
	},
	{
		id: 'coa-coh-1',
		agentId: 'AGT-005',
		agentName: 'Team 1 sentiment boost (3 agents)',
		coachId: 'SUP-001',
		coachName: 'Maria García',
		coachRole: 'SUPERVISOR',
		type: 'GROUP',
		date: '2026-09-19T16:00:00Z',
		durationMin: 60,
		topic: 'Empathy & tone',
		area: 'SENTIMENT_EMOTION',
		subItem: null,
		evidenceCallIds: [],
		talkingPoints: ['Share one recovered call each', 'Practise empathy statements in pairs'],
		notes: '',
		actionItems: [],
		agentCommitment: { acknowledged: false, acknowledgedAt: null, comment: null },
		status: 'SCHEDULED',
		outcome: null,
		followUpDate: null,
		linkedAssignmentIds: [],
		ruleId: null,
		cohortId: 'coh-003',
	},
];

export const COACHING_SESSION_SEEDS: CoachingSessionRecord[] = [
	...CURATED_SESSIONS,
	...buildRosterSessions(),
];

// ── Cohorts ───────────────────────────────────────────────────────────────────

export const COACHING_COHORT_SEEDS: CoachingCohort[] = [
	{
		id: 'coh-001',
		name: 'Q3 new hires',
		description: 'Agents tracked since Q3 who are still completing onboarding.',
		agentIds: ['AGT-018', 'AGT-004', 'AGT-013', 'AGT-021'],
		pathId: 'path-onboarding',
		ruleIds: [],
		tags: ['onboarding'],
		createdBy: 'Elena Ruiz',
		createdByRole: 'QA_MANAGER',
		createdAt: '2026-07-01T09:00:00Z',
	},
	{
		id: 'coh-002',
		name: 'Compliance watchlist — August',
		description: 'Agents who fell below the compliance threshold during August.',
		agentIds: ['AGT-006', 'AGT-007', 'AGT-010', 'AGT-017'],
		pathId: 'path-compliance',
		ruleIds: ['cr-001'],
		tags: ['compliance', 'watchlist'],
		createdBy: 'Elena Ruiz',
		createdByRole: 'QA_MANAGER',
		createdAt: '2026-08-04T09:00:00Z',
	},
	{
		id: 'coh-003',
		name: 'Team 1 sentiment boost',
		description: 'Team 1 agents working on customer sentiment this quarter.',
		agentIds: ['AGT-005', 'AGT-006', 'AGT-004'],
		pathId: 'path-sentiment',
		ruleIds: ['cr-002'],
		tags: ['sentiment', 'team-1'],
		createdBy: 'Maria García',
		createdByRole: 'SUPERVISOR',
		createdAt: '2026-09-01T09:00:00Z',
	},
];

// ── Activity ──────────────────────────────────────────────────────────────────

export const COACHING_ACTIVITY_SEEDS: CoachingActivityEntry[] = [
	{
		id: 'cact-012',
		type: 'RULE_FIRED',
		agentId: 'AGT-004',
		agentName: 'John Smith',
		title: 'Negative emotion share above 30% → De-escalation',
		description: 'Negative emotion share 34% over the last 14 days · 2 items assigned',
		date: '2026-09-11T10:30:00Z',
		area: 'SENTIMENT_EMOTION',
		link: '?tab=agents&agentId=AGT-004',
	},
	{
		id: 'cact-011',
		type: 'ASSIGNED',
		agentId: 'AGT-004',
		agentName: 'John Smith',
		title: 'Compliance certification quiz assigned',
		description: 'Elena Ruiz · due 30 Sep · awaiting acceptance',
		date: '2026-09-10T08:05:00Z',
		area: 'COMPLIANCE',
		link: '?tab=agents&agentId=AGT-004',
	},
	{
		id: 'cact-010',
		type: 'RESCHEDULE_REQUESTED',
		agentId: 'AGT-010',
		agentName: 'Carlos Vega',
		title: 'Asked for 10 more days',
		description: 'Covering two shifts this week, need 10 more days',
		date: '2026-09-09T17:20:00Z',
		area: null,
		link: '?tab=agents&agentId=AGT-010',
	},
	{
		id: 'cact-009',
		type: 'RESCHEDULE_REQUESTED',
		agentId: 'AGT-012',
		agentName: 'Diego Ramírez',
		title: 'Asked for 10 more days',
		description: 'Covering two shifts this week, need 10 more days',
		date: '2026-09-08T12:00:00Z',
		area: null,
		link: '?tab=agents&agentId=AGT-012',
	},
	{
		id: 'cact-008',
		type: 'REMINDER_SENT',
		agentId: 'AGT-006',
		agentName: 'David Brown',
		title: 'Reminder sent — no response for 48 h',
		description: 'Regulatory Disclosures 2026 · overdue',
		date: '2026-09-08T09:15:00Z',
		area: 'COMPLIANCE',
		link: '?tab=agents&agentId=AGT-006',
	},
	{
		id: 'cact-007',
		type: 'SESSION_SCHEDULED',
		agentId: 'AGT-004',
		agentName: 'John Smith',
		title: 'Coaching scheduled: Handling frustrated customers',
		description: 'Maria García · 16 Sep 14:00',
		date: '2026-09-07T15:40:00Z',
		area: 'SENTIMENT_EMOTION',
		link: '?tab=sessions',
	},
	{
		id: 'cact-006',
		type: 'SESSION_COMPLETED',
		agentId: 'AGT-017',
		agentName: 'Nina Patel',
		title: 'Coaching completed: Mandatory disclosures',
		description: 'Elena Ruiz · 2 action items agreed',
		date: '2026-09-04T11:45:00Z',
		area: 'COMPLIANCE',
		link: '?tab=sessions',
	},
	{
		id: 'cact-005',
		type: 'COMPLETED',
		agentId: 'AGT-001',
		agentName: 'Sarah Johnson',
		title: 'Completed: Data Protection on Calls',
		description: 'Measuring impact for the next 30 days',
		date: '2026-09-03T16:10:00Z',
		area: 'COMPLIANCE',
		link: '?tab=agents&agentId=AGT-001',
	},
	{
		id: 'cact-004',
		type: 'COHORT_CREATED',
		agentId: null,
		agentName: null,
		title: 'Cohort created: Team 1 sentiment boost',
		description: 'Maria García · 3 members · Emotional Intelligence on Calls',
		date: '2026-09-01T09:00:00Z',
		area: 'SENTIMENT_EMOTION',
		link: '?tab=cohorts',
	},
	{
		id: 'cact-003',
		type: 'IMPACT_MEASURED',
		agentId: 'AGT-004',
		agentName: 'John Smith',
		title: 'Impact measured: Needs Assessment Questions',
		description: 'QA score improved 8 points 30 days after completion',
		date: '2026-08-29T09:00:00Z',
		area: 'QUALITY_ASSURANCE',
		link: '?tab=impact',
	},
	{
		id: 'cact-002',
		type: 'SESSION_MISSED',
		agentId: 'AGT-006',
		agentName: 'David Brown',
		title: 'Coaching missed: Handling frustrated customers',
		description: 'Rescheduled as a side-by-side on 15 Sep',
		date: '2026-08-28T15:00:00Z',
		area: 'SENTIMENT_EMOTION',
		link: '?tab=sessions',
	},
	{
		id: 'cact-001',
		type: 'RULE_FIRED',
		agentId: 'AGT-017',
		agentName: 'Nina Patel',
		title: 'Do-Not-Call violation → DNC refresher',
		description: '1 violation on call-001 · refresher assigned, session booked',
		date: '2026-08-27T15:00:00Z',
		area: 'COMPLIANCE',
		link: '?tab=agents&agentId=AGT-017',
	},
];
