// Extracted mock data from burnout-risk-widget campaigns pages

import type {
  Campaign,
  CampaignDetail,
  ContactList,
  Evaluation,
  CallEvaluationResult,
  ConversationEvaluation,
  QATest,
  Aspect,
} from './types';

export const mockCampaigns: Campaign[] = [
  {
    id: '1',
    name: 'Q2 Sales Performance',
    description: 'Evaluate sales calls from Q2 2026',
    contactLists: 8,
    status: 'active',
    callsScored: 45,
    evaluationsCompleted: 8,
    evaluationType: 'automatic',
    createdAt: '2026-06-01',
    type: 'external',
  },
  {
    id: '2',
    name: 'Customer Support Quality',
    description: 'CS team performance evaluation',
    contactLists: 12,
    status: 'active',
    callsScored: 87,
    evaluationsCompleted: 6,
    evaluationType: 'mixed',
    createdAt: '2026-05-15',
    type: 'cmx',
  },
  {
    id: '3',
    name: 'New Hire Training - June',
    description: 'Onboarding evaluation for new agents',
    contactLists: 5,
    status: 'pending',
    callsScored: 12,
    evaluationsCompleted: 2,
    evaluationType: 'manual',
    createdAt: '2026-06-10',
    type: 'external',
  },
  {
    id: '4',
    name: 'Compliance Audit Wave 2',
    description: 'Regulatory compliance evaluation',
    contactLists: 15,
    status: 'active',
    callsScored: 234,
    evaluationsCompleted: 15,
    evaluationType: 'automatic',
    createdAt: '2026-05-01',
    type: 'cmx',
  },
  {
    id: '5',
    name: 'Agent Coaching Program',
    description: 'Performance improvement coaching evaluations',
    contactLists: 4,
    status: 'paused',
    callsScored: 28,
    evaluationsCompleted: 4,
    evaluationType: 'manual',
    createdAt: '2026-04-20',
    type: 'external',
  },
];

export const mockCampaignDetails: Record<string, CampaignDetail> = {
  '1': {
    id: '1',
    name: 'Q2 Sales Performance',
    type: 'sales',
    responsibleContact: 'John Smith',
    description: 'Quarterly evaluation of sales team performance and call quality standards',
    evaluatorModel: 'Pro Sales Evaluator v2.5',
  },
  '2': {
    id: '2',
    name: 'Customer Support Review',
    type: 'retention',
    responsibleContact: 'Sarah Johnson',
    description: 'Ongoing quality assurance for customer support interactions',
    evaluatorModel: 'Customer Service Evaluator v3.0',
  },
  '3': {
    id: '3',
    name: 'Agent Training Q2',
    type: 'activation',
    responsibleContact: 'Mike Wilson',
    description: 'New agent onboarding and training evaluation program',
    evaluatorModel: 'Pro Sales Evaluator v2.3',
  },
};

export const mockContactLists: ContactList[] = [
  {
    id: 'list1',
    name: 'Q2 Sales Performance',
    callCount: 12,
    status: 'completed',
    startDate: '2026-06-15',
    endDate: '2026-06-30',
  },
  {
    id: 'list2',
    name: 'Q2 Sales Performance',
    callCount: 8,
    status: 'in-progress',
    startDate: '2026-07-01',
    endDate: '2026-07-15',
  },
  {
    id: 'list3',
    name: 'Q2 Sales Performance',
    callCount: 10,
    status: 'in-progress',
    startDate: '2026-07-16',
    endDate: '2026-07-31',
  },
  {
    id: 'list4',
    name: 'Q2 Sales Performance',
    callCount: 9,
    status: 'completed',
    startDate: '2026-06-01',
    endDate: '2026-06-14',
  },
];

export const mockEvaluations: Evaluation[] = [
  {
    id: 'eval1',
    name: 'Sales Quality Q2',
    status: 'completed',
    type: 'automatic',
    finalScore: 87,
    result: 'passed',
    evaluatedPercentage: 100,
    agent: 'Claude Sonnet 4.5',
    llmModel: 'claude-sonnet-4-6',
    contactListIds: ['list1', 'list2'],
    createdDate: '2026-06-15',
  },
  {
    id: 'eval2',
    name: 'Compliance Review',
    status: 'completed',
    type: 'automatic',
    finalScore: 0,
    result: 'passed',
    evaluatedPercentage: 65,
    agent: 'Claude Opus',
    llmModel: 'claude-opus-4-6',
    contactListIds: ['list3', 'list4'],
    createdDate: '2026-07-01',
  },
];

export const mockResults: CallEvaluationResult[] = [
  {
    id: '1',
    callId: 'CALL-001',
    filename: 'call_001.mp3',
    agentName: 'John Smith',
    aiScore: 85,
    finalScore: 88,
    delta: 3,
    overridden: true,
    mode: 'auto',
    evaluatorModel: 'claude-sonnet-4-6',
    evaluatedAt: '2026-06-22 14:30',
  },
  {
    id: '2',
    callId: 'CALL-002',
    filename: 'call_002.mp3',
    agentName: 'Sarah Jones',
    aiScore: 92,
    finalScore: 92,
    delta: 0,
    overridden: false,
    mode: 'auto',
    evaluatorModel: 'claude-sonnet-4-6',
    evaluatedAt: '2026-06-22 14:35',
  },
  {
    id: '3',
    callId: 'CALL-003',
    filename: 'call_003.mp3',
    agentName: 'Mike Wilson',
    aiScore: 0,
    finalScore: 78,
    delta: 78,
    overridden: true,
    mode: 'manual',
    evaluatorModel: 'manual',
    evaluatedAt: '2026-06-22 15:00',
  },
  {
    id: '4',
    callId: 'CALL-004',
    filename: 'call_004.mp3',
    agentName: 'John Smith',
    aiScore: 76,
    finalScore: 76,
    delta: 0,
    overridden: false,
    mode: 'auto',
    evaluatorModel: 'claude-sonnet-4-6',
    evaluatedAt: '2026-06-22 15:10',
  },
  {
    id: '5',
    callId: 'CALL-005',
    filename: 'call_005.mp3',
    agentName: 'Sarah Jones',
    aiScore: 88,
    finalScore: 85,
    delta: -3,
    overridden: true,
    mode: 'auto',
    evaluatorModel: 'claude-sonnet-4-6',
    evaluatedAt: '2026-06-22 15:20',
  },
];

export const mockConversationEvaluations: ConversationEvaluation[] = [
  {
    id: '1',
    type: 'sentiment-analysis',
    score: 87,
    status: 'completed',
  },
  {
    id: '2',
    type: 'business-insights',
    score: null,
    status: 'not-evaluated',
  },
  {
    id: '3',
    type: 'compliance',
    score: 94,
    status: 'completed',
  },
];

export const mockCampaignNames: Record<string, string> = {
  '1': 'Q2 Sales Performance',
  '2': 'Customer Support Review',
  '3': 'Agent Training Q2',
};

const mockEvaluationAspects: Aspect[] = [
  {
    id: 'asp1',
    name: 'Sales Techniques',
    description: 'Evaluation of sales techniques and methodologies',
    items: [
      {
        id: 'item1',
        name: 'Opening Statement',
        errorType: 'critical-business',
        answerType: 'yes-no',
        description: 'Did the agent provide a proper opening statement?',
        valuation: 10,
      },
      {
        id: 'item2',
        name: 'Needs Assessment',
        errorType: 'critical-business',
        answerType: 'yes-no',
        description: 'Did the agent properly assess customer needs?',
        valuation: 15,
      },
    ],
  },
  {
    id: 'asp2',
    name: 'Compliance',
    description: 'Regulatory compliance checks',
    items: [
      {
        id: 'item3',
        name: 'Disclosure Statement',
        errorType: 'critical-compliance',
        answerType: 'yes-no',
        description: 'Was the required disclosure statement provided?',
        valuation: 20,
      },
    ],
  },
];

export const mockQATests: QATest[] = [
  {
    id: 'test1',
    name: 'Sales Quality Q2 2026',
    qaType: 'sales',
    createdDate: '2026-06-01',
    evaluatedCampaigns: 3,
    createdBy: 'Quality Team',
    description: 'Comprehensive quality assurance for Q2 sales campaigns',
    aspects: mockEvaluationAspects,
    status: 'ready',
  },
  {
    id: 'test2',
    name: 'Compliance Audit Q3',
    qaType: 'activation',
    createdDate: '2026-07-01',
    evaluatedCampaigns: 5,
    createdBy: 'Compliance Team',
    description: 'Regulatory compliance evaluation',
    status: 'ready',
  },
];
