import type { Call } from './types';
import { calculateTonePercentages } from './calculateTonePercentages';

export const mockCalls: Call[] = [
	{
		id: 'call-001',
		agentId: 'agent-001',
		agentName: 'Sarah Smith',
		customerId: 'cust-042',
		customerName: 'John Doe',
		isRepeatCustomer: true,
		callCount: 5,
		date: '2026-08-06T14:15:00Z',
		duration: 222,
		sentiment: 2.8,
		emotions: ['frustration', 'anger', 'sadness'],
		issueTag: 'billing',
		transcriptUrl: '/calls/transcripts/call-001.txt',
		audioUrl: '/calls/audio/call-001.mp3',
		transcript: [
			{
				timestamp: 0,
				speaker: 'agent',
				text: 'Hello, thank you for calling. How can I help you today?',
				tone: 'polite',
				emotion: 'neutral',
				sentiment: 4.0,
				empathy: 'high',
			},
			{
				timestamp: 15,
				speaker: 'customer',
				text: 'Yeah hi, I have an issue with my bill. It charged me twice.',
				emotion: 'neutral',
				sentiment: 3.0,
			},
			{
				timestamp: 30,
				speaker: 'agent',
				text: 'I understand. Let me check that for you right away.',
				tone: 'professional',
				emotion: 'neutral',
				sentiment: 3.5,
				empathy: 'medium',
			},
			{
				timestamp: 45,
				speaker: 'agent',
				text: 'I can see here that there are two charges from last month. Let me look into this.',
				tone: 'professional',
				emotion: 'neutral',
				sentiment: 3.5,
				empathy: 'medium',
			},
			{
				timestamp: 60,
				speaker: 'customer',
				text: 'This is ridiculous. Why do I have to deal with this? I was charged twice!',
				emotion: 'anger',
				sentiment: 2.0,
			},
			{
				timestamp: 80,
				speaker: 'agent',
				text: 'I see the duplicate charge. Let me process a refund for you immediately.',
				tone: 'professional',
				emotion: 'neutral',
				sentiment: 3.5,
				empathy: 'low',
			},
			{
				timestamp: 100,
				speaker: 'agent',
				text: 'The refund will appear in your account within 3-5 business days.',
				tone: 'professional',
				emotion: 'neutral',
				sentiment: 3.5,
				empathy: 'low',
			},
			{
				timestamp: 180,
				speaker: 'customer',
				text: 'Fine. Whatever. Is there anything else?',
				emotion: 'sadness',
				sentiment: 2.5,
			},
			{
				timestamp: 200,
				speaker: 'agent',
				text: 'We appreciate your patience. Is there anything else I can help with?',
				tone: 'polite',
				emotion: 'neutral',
				sentiment: 3.8,
				empathy: 'medium',
			},
		],
	},
	{
		id: 'call-002',
		agentId: 'agent-002',
		agentName: 'Michael Johnson',
		customerId: 'cust-015',
		customerName: 'Maria Garcia',
		isRepeatCustomer: false,
		date: '2026-08-06T15:42:00Z',
		duration: 315,
		sentiment: 4.2,
		emotions: ['satisfaction', 'excitement'],
		issueTag: 'order',
		transcriptUrl: '/calls/transcripts/call-002.txt',
		audioUrl: '/calls/audio/call-002.mp3',
		transcript: [
			{
				timestamp: 0,
				speaker: 'agent',
				text: 'Hello Maria! Thank you so much for choosing us. How are you doing today?',
				tone: 'polite',
				emotion: 'neutral',
				sentiment: 4.2,
				empathy: 'high',
			},
			{
				timestamp: 10,
				speaker: 'customer',
				text: 'Hi! I just received my order and I absolutely love it!',
				emotion: 'satisfaction',
				sentiment: 4.5,
			},
			{
				timestamp: 25,
				speaker: 'agent',
				text: "That's wonderful to hear! I'm so glad you're happy with your purchase.",
				tone: 'empathetic',
				emotion: 'neutral',
				sentiment: 4.3,
				empathy: 'high',
			},
			{
				timestamp: 40,
				speaker: 'agent',
				text: 'Your satisfaction means everything to us. Is there anything else I can help you with?',
				tone: 'empathetic',
				emotion: 'neutral',
				sentiment: 4.3,
				empathy: 'high',
			},
			{
				timestamp: 55,
				speaker: 'customer',
				text: 'No, everything is perfect. You guys are great!',
				emotion: 'excitement',
				sentiment: 4.8,
			},
			{
				timestamp: 70,
				speaker: 'agent',
				text: 'Thank you so much! Please feel free to reach out anytime you need us. We really value your business.',
				tone: 'empathetic',
				emotion: 'neutral',
				sentiment: 4.4,
				empathy: 'high',
			},
		],
	},
	{
		id: 'call-003',
		agentId: 'agent-003',
		agentName: 'Emily Brown',
		customerId: 'cust-089',
		customerName: 'David Chen',
		isRepeatCustomer: true,
		callCount: 3,
		date: '2026-08-06T11:20:00Z',
		duration: 180,
		sentiment: 3.2,
		emotions: ['frustration', 'neutral'],
		issueTag: 'technical',
		transcriptUrl: '/calls/transcripts/call-003.txt',
		audioUrl: '/calls/audio/call-003.mp3',
		transcript: [
			{
				timestamp: 0,
				speaker: 'agent',
				text: 'Hi David, thanks for calling back. I know you were having technical issues.',
				tone: 'polite',
				emotion: 'neutral',
				sentiment: 3.8,
				empathy: 'high',
			},
			{
				timestamp: 15,
				speaker: 'customer',
				text: 'Yeah, the app keeps crashing. I already called twice about this.',
				emotion: 'frustration',
				sentiment: 2.8,
			},
			{
				timestamp: 30,
				speaker: 'agent',
				text: 'I completely understand your frustration. We take these issues seriously.',
				tone: 'empathetic',
				emotion: 'neutral',
				sentiment: 4.0,
				empathy: 'high',
			},
			{
				timestamp: 50,
				speaker: 'agent',
				text: 'Let me escalate this to our engineering team right away. They should have a fix within 24 hours.',
				tone: 'professional',
				emotion: 'neutral',
				sentiment: 3.7,
				empathy: 'medium',
			},
			{
				timestamp: 80,
				speaker: 'customer',
				text: 'Finally. I need this fixed soon.',
				emotion: 'frustration',
				sentiment: 3.0,
			},
			{
				timestamp: 100,
				speaker: 'agent',
				text: 'You have my commitment. I will personally follow up with you tomorrow.',
				tone: 'empathetic',
				emotion: 'neutral',
				sentiment: 4.1,
				empathy: 'high',
			},
		],
	},
	{
		id: 'call-004',
		agentId: 'agent-004',
		agentName: 'Robert Wilson',
		customerId: 'cust-067',
		customerName: 'Lisa Anderson',
		isRepeatCustomer: false,
		date: '2026-08-05T16:30:00Z',
		duration: 240,
		sentiment: 3.9,
		emotions: ['neutral', 'satisfaction'],
		issueTag: 'complaint',
		transcriptUrl: '/calls/transcripts/call-004.txt',
		audioUrl: '/calls/audio/call-004.mp3',
		transcript: [
			{
				timestamp: 0,
				speaker: 'agent',
				text: 'Hello, thank you for contacting us. What brings you in today?',
				tone: 'professional',
				emotion: 'neutral',
				sentiment: 3.8,
				empathy: 'medium',
			},
			{
				timestamp: 12,
				speaker: 'customer',
				text: 'I received a damaged item in my shipment.',
				emotion: 'neutral',
				sentiment: 3.2,
			},
			{
				timestamp: 25,
				speaker: 'agent',
				text: "I'm really sorry to hear that happened. Let's make this right for you.",
				tone: 'empathetic',
				emotion: 'neutral',
				sentiment: 4.1,
				empathy: 'high',
			},
			{
				timestamp: 45,
				speaker: 'agent',
				text: 'I can send you a replacement immediately, and we can arrange a pickup for the damaged item.',
				tone: 'professional',
				emotion: 'neutral',
				sentiment: 3.9,
				empathy: 'medium',
			},
			{
				timestamp: 70,
				speaker: 'customer',
				text: 'Oh great! That would be perfect.',
				emotion: 'satisfaction',
				sentiment: 4.3,
			},
			{
				timestamp: 85,
				speaker: 'agent',
				text: 'Your replacement will arrive within 2 business days. Thank you for your patience and understanding.',
				tone: 'professional',
				emotion: 'neutral',
				sentiment: 3.9,
				empathy: 'medium',
			},
		],
	},
	{
		id: 'call-005',
		agentId: 'agent-001',
		agentName: 'Sarah Smith',
		customerId: 'cust-124',
		customerName: 'James Thompson',
		isRepeatCustomer: true,
		callCount: 8,
		date: '2026-08-05T13:15:00Z',
		duration: 198,
		sentiment: 4.5,
		emotions: ['satisfaction', 'excitement'],
		issueTag: 'feedback',
		transcriptUrl: '/calls/transcripts/call-005.txt',
		audioUrl: '/calls/audio/call-005.mp3',
		transcript: [
			{
				timestamp: 0,
				speaker: 'agent',
				text: 'Hi James! Great to hear from you again! What can I do for you?',
				tone: 'polite',
				emotion: 'neutral',
				sentiment: 4.3,
				empathy: 'high',
			},
			{
				timestamp: 10,
				speaker: 'customer',
				text: 'I just wanted to say how impressed I am with your new feature rollout.',
				emotion: 'excitement',
				sentiment: 4.7,
			},
			{
				timestamp: 25,
				speaker: 'agent',
				text: 'Thank you so much! We worked really hard on that. Your feedback actually helped shape it.',
				tone: 'empathetic',
				emotion: 'neutral',
				sentiment: 4.4,
				empathy: 'high',
			},
			{
				timestamp: 50,
				speaker: 'customer',
				text: "It's exactly what I needed. You guys really listen to your customers.",
				emotion: 'satisfaction',
				sentiment: 4.8,
			},
			{
				timestamp: 70,
				speaker: 'agent',
				text: "That means the world to us, James. You're one of our most valued customers.",
				tone: 'empathetic',
				emotion: 'neutral',
				sentiment: 4.5,
				empathy: 'high',
			},
		],
	},
	{
		id: 'call-006',
		agentId: 'agent-002',
		agentName: 'Michael Johnson',
		customerId: 'cust-201',
		customerName: 'Patricia Martinez',
		isRepeatCustomer: false,
		date: '2026-08-04T10:45:00Z',
		duration: 420,
		sentiment: 2.5,
		emotions: ['anger', 'frustration'],
		issueTag: 'billing',
		transcriptUrl: '/calls/transcripts/call-006.txt',
		audioUrl: '/calls/audio/call-006.mp3',
		transcript: [
			{
				timestamp: 0,
				speaker: 'agent',
				text: 'Thank you for calling. How can I assist you?',
				tone: 'professional',
				emotion: 'neutral',
				sentiment: 3.5,
				empathy: 'medium',
			},
			{
				timestamp: 10,
				speaker: 'customer',
				text: "I've been trying to resolve a billing issue for a month. No one has helped me!",
				emotion: 'anger',
				sentiment: 2.2,
			},
			{
				timestamp: 30,
				speaker: 'agent',
				text: 'Let me look into your account and see what we can do.',
				tone: 'professional',
				emotion: 'neutral',
				sentiment: 3.3,
				empathy: 'low',
			},
			{
				timestamp: 60,
				speaker: 'customer',
				text: "I'm extremely frustrated. This is unacceptable service.",
				emotion: 'anger',
				sentiment: 2.0,
			},
			{
				timestamp: 90,
				speaker: 'agent',
				text: 'I can see there were several attempts to reach you. Let me resolve this now.',
				tone: 'professional',
				emotion: 'neutral',
				sentiment: 3.4,
				empathy: 'low',
			},
			{
				timestamp: 150,
				speaker: 'customer',
				text: 'I just want my money back and a resolution.',
				emotion: 'frustration',
				sentiment: 2.7,
			},
			{
				timestamp: 200,
				speaker: 'agent',
				text: 'I am processing a full refund for you now.',
				tone: 'professional',
				emotion: 'neutral',
				sentiment: 3.6,
				empathy: 'low',
			},
		],
	},
	{
		id: 'call-007',
		agentId: 'agent-003',
		agentName: 'Emily Brown',
		customerId: 'cust-156',
		customerName: 'William Davis',
		isRepeatCustomer: true,
		callCount: 2,
		date: '2026-08-04T14:00:00Z',
		duration: 165,
		sentiment: 4.1,
		emotions: ['satisfaction'],
		issueTag: 'order',
		transcriptUrl: '/calls/transcripts/call-007.txt',
		audioUrl: '/calls/audio/call-007.mp3',
		transcript: [
			{
				timestamp: 0,
				speaker: 'agent',
				text: 'Hi William, wonderful to hear from you again!',
				tone: 'polite',
				emotion: 'neutral',
				sentiment: 4.2,
				empathy: 'high',
			},
			{
				timestamp: 10,
				speaker: 'customer',
				text: 'Hey! I wanted to place another order and had a quick question.',
				emotion: 'neutral',
				sentiment: 3.9,
			},
			{
				timestamp: 20,
				speaker: 'agent',
				text: 'Of course! I remember your preferences from last time.',
				tone: 'empathetic',
				emotion: 'neutral',
				sentiment: 4.3,
				empathy: 'high',
			},
			{
				timestamp: 40,
				speaker: 'customer',
				text: 'Can I get the bulk discount again?',
				emotion: 'neutral',
				sentiment: 3.8,
			},
			{
				timestamp: 55,
				speaker: 'agent',
				text: 'Absolutely! And I can apply an additional loyalty discount for you.',
				tone: 'empathetic',
				emotion: 'neutral',
				sentiment: 4.4,
				empathy: 'high',
			},
			{
				timestamp: 85,
				speaker: 'customer',
				text: "That's excellent! I really appreciate it.",
				emotion: 'satisfaction',
				sentiment: 4.5,
			},
		],
	},
	{
		id: 'call-008',
		agentId: 'agent-004',
		agentName: 'Robert Wilson',
		customerId: 'cust-088',
		customerName: 'Jennifer White',
		isRepeatCustomer: false,
		date: '2026-08-03T09:30:00Z',
		duration: 276,
		sentiment: 3.6,
		emotions: ['neutral', 'satisfaction'],
		issueTag: 'technical',
		transcriptUrl: '/calls/transcripts/call-008.txt',
		audioUrl: '/calls/audio/call-008.mp3',
		transcript: [
			{
				timestamp: 0,
				speaker: 'agent',
				text: "Hello! I'm Robert. How can I help you today?",
				tone: 'polite',
				emotion: 'neutral',
				sentiment: 3.9,
				empathy: 'high',
			},
			{
				timestamp: 12,
				speaker: 'customer',
				text: 'I need help setting up the software. I got it installed but am confused about the settings.',
				emotion: 'neutral',
				sentiment: 3.4,
			},
			{
				timestamp: 30,
				speaker: 'agent',
				text: 'No problem at all. These settings can be confusing. Let me walk you through it.',
				tone: 'empathetic',
				emotion: 'neutral',
				sentiment: 4.1,
				empathy: 'high',
			},
			{
				timestamp: 60,
				speaker: 'agent',
				text: "Here's what each setting does. First, you'll want to set this to your preference.",
				tone: 'professional',
				emotion: 'neutral',
				sentiment: 3.8,
				empathy: 'medium',
			},
			{
				timestamp: 120,
				speaker: 'customer',
				text: 'Oh, that makes sense now! You explained it really well.',
				emotion: 'satisfaction',
				sentiment: 4.2,
			},
			{
				timestamp: 150,
				speaker: 'agent',
				text: 'Happy to help! Feel free to reach out if you have any other questions.',
				tone: 'polite',
				emotion: 'neutral',
				sentiment: 4.0,
				empathy: 'high',
			},
		],
	},
];

// Calculate tone breakdowns for all calls
export const getCallsWithToneBreakdown = (): Call[] => {
	return mockCalls.map((call) => ({
		...call,
		toneBreakdown: calculateTonePercentages(call.transcript),
	}));
};

export default getCallsWithToneBreakdown();
