import type { EvaluationDisputeSummary, PaginatedResponse } from '~/models/qa';

const mockDisputes: EvaluationDisputeSummary[] = [
	{
		id: 1001,
		sourceEvaluationId: 101,
		resultingEvaluationId: 102,
		sourceVersion: 1,
		sourceEvaluatorType: 'AI',
		sourceFormName: 'QA',
		sourceAgentName: 'Sarah Johnson',
		sourceEvaluatorAgentName: null,
		sourceEvaluatorUserName: 'AI Evaluator v2.1',
		sourceCampaignName: 'Q2 Sales Performance',
		sourceInteractionRef: 'CALL-2026-07-001',
		resultingEvaluatorType: 'HUMAN',
		resultingFormName: 'QA (Corrected)',
		resultingAgentName: 'Sarah Johnson',
		resultingEvaluatorAgentName: null,
		resultingEvaluatorUserName: 'John Smith',
		resultingCampaignName: 'Q2 Sales Performance',
		resultingInteractionRef: 'CALL-2026-07-001',
		disputedByUserId: 201,
		disputedByUserName: 'Maria Garcia',
		reason:
			'The AI evaluation marked the greeting response as incomplete, but the agent clearly provided a complete greeting that met all requirements.',
		before: {
			overallScore: 72,
			overallScorePct: 72,
			maxScore: 100,
		},
		after: {
			overallScore: 85,
			overallScorePct: 85,
			maxScore: 100,
		},
		scoreDelta: 13,
		resultingVersion: 2,
		createdAt: '2026-07-28T14:32:00Z',
		status: 'approved',
		disputedQuestionIds: [1, 2],
	},
	{
		id: 1002,
		sourceEvaluationId: 103,
		resultingEvaluationId: 104,
		sourceVersion: 1,
		sourceEvaluatorType: 'AI',
		sourceFormName: 'QA',
		sourceAgentName: 'Michael Chen',
		sourceEvaluatorAgentName: null,
		sourceEvaluatorUserName: 'AI Evaluator v2.1',
		sourceCampaignName: 'Q2 Sales Performance',
		sourceInteractionRef: 'CALL-2026-07-002',
		resultingEvaluatorType: 'HUMAN',
		resultingFormName: 'QA (Corrected)',
		resultingAgentName: 'Michael Chen',
		resultingEvaluatorAgentName: null,
		resultingEvaluatorUserName: 'Robert Chen',
		resultingCampaignName: 'Q2 Sales Performance',
		resultingInteractionRef: 'CALL-2026-07-002',
		disputedByUserId: 202,
		disputedByUserName: 'John Smith',
		reason:
			'Disagreement on objection handling scoring. The agent successfully handled the price objection with evidence and justification.',
		before: {
			overallScore: 68,
			overallScorePct: 68,
			maxScore: 100,
		},
		after: {
			overallScore: 78,
			overallScorePct: 78,
			maxScore: 100,
		},
		scoreDelta: 10,
		resultingVersion: 2,
		createdAt: '2026-07-27T10:15:00Z',
		status: 'approved',
		disputedQuestionIds: [3, 5],
	},
	{
		id: 1003,
		sourceEvaluationId: 105,
		resultingEvaluationId: 106,
		sourceVersion: 1,
		sourceEvaluatorType: 'AI',
		sourceFormName: 'Compliance',
		sourceAgentName: 'Jessica Martinez',
		sourceEvaluatorAgentName: null,
		sourceEvaluatorUserName: 'AI Evaluator v2.1',
		sourceCampaignName: 'Customer Support Quality',
		sourceInteractionRef: 'CALL-2026-07-003',
		resultingEvaluatorType: 'HUMAN',
		resultingFormName: 'Compliance (Corrected)',
		resultingAgentName: 'Jessica Martinez',
		resultingEvaluatorAgentName: null,
		resultingEvaluatorUserName: 'Maria Garcia',
		resultingCampaignName: 'Customer Support Quality',
		resultingInteractionRef: 'CALL-2026-07-003',
		disputedByUserId: 203,
		disputedByUserName: 'Robert Chen',
		reason:
			'The disclosure statement was provided verbally, which meets compliance requirements even though AI flagged it as missing.',
		before: {
			overallScore: 65,
			overallScorePct: 65,
			maxScore: 100,
		},
		after: {
			overallScore: 82,
			overallScorePct: 82,
			maxScore: 100,
		},
		scoreDelta: 17,
		resultingVersion: 2,
		createdAt: '2026-07-26T09:45:00Z',
		status: 'open',
		disputedQuestionIds: [1, 2],
	},
	{
		id: 1004,
		sourceEvaluationId: 107,
		resultingEvaluationId: 108,
		sourceVersion: 1,
		sourceEvaluatorType: 'AI',
		sourceFormName: 'QA',
		sourceAgentName: 'David Thompson',
		sourceEvaluatorAgentName: null,
		sourceEvaluatorUserName: 'AI Evaluator v2.1',
		sourceCampaignName: 'Customer Support Quality',
		sourceInteractionRef: 'CALL-2026-07-004',
		resultingEvaluatorType: 'HUMAN',
		resultingFormName: 'QA (Corrected)',
		resultingAgentName: 'David Thompson',
		resultingEvaluatorAgentName: null,
		resultingEvaluatorUserName: 'John Smith',
		resultingCampaignName: 'Customer Support Quality',
		resultingInteractionRef: 'CALL-2026-07-004',
		disputedByUserId: 204,
		disputedByUserName: 'Maria Garcia',
		reason:
			'The negative sentiment score was incorrectly marked as negative. The agent was using empathetic language which should reflect positively.',
		before: {
			overallScore: 60,
			overallScorePct: 60,
			maxScore: 100,
		},
		after: {
			overallScore: 75,
			overallScorePct: 75,
			maxScore: 100,
		},
		scoreDelta: 15,
		resultingVersion: 2,
		createdAt: '2026-07-25T16:20:00Z',
		status: 'rejected',
	},
	{
		id: 1005,
		sourceEvaluationId: 109,
		resultingEvaluationId: 110,
		sourceVersion: 1,
		sourceEvaluatorType: 'AI',
		sourceFormName: 'QA',
		sourceAgentName: 'Emily Rodriguez',
		sourceEvaluatorAgentName: null,
		sourceEvaluatorUserName: 'AI Evaluator v2.1',
		sourceCampaignName: 'Outbound Campaign 2026',
		sourceInteractionRef: 'CALL-2026-07-005',
		resultingEvaluatorType: 'HUMAN',
		resultingFormName: 'QA (Corrected)',
		resultingAgentName: 'Emily Rodriguez',
		resultingEvaluatorAgentName: null,
		resultingEvaluatorUserName: 'Robert Chen',
		resultingCampaignName: 'Outbound Campaign 2026',
		resultingInteractionRef: 'CALL-2026-07-005',
		disputedByUserId: 201,
		disputedByUserName: 'John Smith',
		reason:
			'The closing technique was marked incomplete, but the agent successfully secured a callback within the target timeframe.',
		before: {
			overallScore: 70,
			overallScorePct: 70,
			maxScore: 100,
		},
		after: {
			overallScore: 84,
			overallScorePct: 84,
			maxScore: 100,
		},
		scoreDelta: 14,
		resultingVersion: 2,
		createdAt: '2026-07-24T11:30:00Z',
		status: 'approved',
	},
	{
		id: 1006,
		sourceEvaluationId: 111,
		resultingEvaluationId: 112,
		sourceVersion: 1,
		sourceEvaluatorType: 'AI',
		sourceFormName: 'QA',
		sourceAgentName: 'James Wilson',
		sourceEvaluatorAgentName: null,
		sourceEvaluatorUserName: 'AI Evaluator v2.1',
		sourceCampaignName: 'Customer Support Quality',
		sourceInteractionRef: 'CALL-2026-07-006',
		resultingEvaluatorType: 'HUMAN',
		resultingFormName: 'QA (Corrected)',
		resultingAgentName: 'James Wilson',
		resultingEvaluatorAgentName: null,
		resultingEvaluatorUserName: 'Maria Garcia',
		resultingCampaignName: 'Customer Support Quality',
		resultingInteractionRef: 'CALL-2026-07-006',
		disputedByUserId: 202,
		disputedByUserName: 'Robert Chen',
		reason:
			'Knowledge demonstration score was penalized despite agent providing accurate and detailed product information throughout the call.',
		before: {
			overallScore: 74,
			overallScorePct: 74,
			maxScore: 100,
		},
		after: {
			overallScore: 88,
			overallScorePct: 88,
			maxScore: 100,
		},
		scoreDelta: 14,
		resultingVersion: 2,
		createdAt: '2026-07-23T13:45:00Z',
		status: 'open',
	},
	{
		id: 1007,
		sourceEvaluationId: 113,
		resultingEvaluationId: 114,
		sourceVersion: 1,
		sourceEvaluatorType: 'AI',
		sourceFormName: 'Compliance',
		sourceAgentName: 'Lisa Anderson',
		sourceEvaluatorAgentName: null,
		sourceEvaluatorUserName: 'AI Evaluator v2.1',
		sourceCampaignName: 'Q2 Sales Performance',
		sourceInteractionRef: 'CALL-2026-07-007',
		resultingEvaluatorType: 'HUMAN',
		resultingFormName: 'Compliance (Corrected)',
		resultingAgentName: 'Lisa Anderson',
		resultingEvaluatorAgentName: null,
		resultingEvaluatorUserName: 'John Smith',
		resultingCampaignName: 'Q2 Sales Performance',
		resultingInteractionRef: 'CALL-2026-07-007',
		disputedByUserId: 203,
		disputedByUserName: 'Maria Garcia',
		reason:
			'The consent confirmation was inferred from context, which is acceptable per our compliance guidelines for this call type.',
		before: {
			overallScore: 69,
			overallScorePct: 69,
			maxScore: 100,
		},
		after: {
			overallScore: 80,
			overallScorePct: 80,
			maxScore: 100,
		},
		scoreDelta: 11,
		resultingVersion: 2,
		createdAt: '2026-07-22T08:00:00Z',
		status: 'approved',
	},
	{
		id: 1008,
		sourceEvaluationId: 115,
		resultingEvaluationId: 116,
		sourceVersion: 1,
		sourceEvaluatorType: 'AI',
		sourceFormName: 'QA',
		sourceAgentName: 'Kevin Lee',
		sourceEvaluatorAgentName: null,
		sourceEvaluatorUserName: 'AI Evaluator v2.1',
		sourceCampaignName: 'Outbound Campaign 2026',
		sourceInteractionRef: 'CALL-2026-07-008',
		resultingEvaluatorType: 'HUMAN',
		resultingFormName: 'QA (Corrected)',
		resultingAgentName: 'Kevin Lee',
		resultingEvaluatorAgentName: null,
		resultingEvaluatorUserName: 'Robert Chen',
		resultingCampaignName: 'Outbound Campaign 2026',
		resultingInteractionRef: 'CALL-2026-07-008',
		disputedByUserId: 204,
		disputedByUserName: 'John Smith',
		reason:
			'The objection handling approach was creative and resulted in a sale. Different technique than expected but highly effective.',
		before: {
			overallScore: 71,
			overallScorePct: 71,
			maxScore: 100,
		},
		after: {
			overallScore: 86,
			overallScorePct: 86,
			maxScore: 100,
		},
		scoreDelta: 15,
		resultingVersion: 2,
		createdAt: '2026-07-21T15:30:00Z',
		status: 'open',
	},
	{
		id: 1009,
		sourceEvaluationId: 117,
		resultingEvaluationId: 118,
		sourceVersion: 1,
		sourceEvaluatorType: 'AI',
		sourceFormName: 'QA',
		sourceAgentName: 'Amanda Brown',
		sourceEvaluatorAgentName: null,
		sourceEvaluatorUserName: 'AI Evaluator v2.1',
		sourceCampaignName: 'Customer Support Quality',
		sourceInteractionRef: 'CALL-2026-07-009',
		resultingEvaluatorType: 'HUMAN',
		resultingFormName: 'QA (Corrected)',
		resultingAgentName: 'Amanda Brown',
		resultingEvaluatorAgentName: null,
		resultingEvaluatorUserName: 'Maria Garcia',
		resultingCampaignName: 'Customer Support Quality',
		resultingInteractionRef: 'CALL-2026-07-009',
		disputedByUserId: 201,
		disputedByUserName: 'Robert Chen',
		reason:
			'First call resolution was achieved despite AI marking the resolution as incomplete. Customer confirmed satisfaction at end of call.',
		before: {
			overallScore: 73,
			overallScorePct: 73,
			maxScore: 100,
		},
		after: {
			overallScore: 87,
			overallScorePct: 87,
			maxScore: 100,
		},
		scoreDelta: 14,
		resultingVersion: 2,
		createdAt: '2026-07-20T10:15:00Z',
		status: 'rejected',
	},
	{
		id: 1010,
		sourceEvaluationId: 119,
		resultingEvaluationId: 120,
		sourceVersion: 1,
		sourceEvaluatorType: 'AI',
		sourceFormName: 'Compliance',
		sourceAgentName: 'Christopher Davis',
		sourceEvaluatorAgentName: null,
		sourceEvaluatorUserName: 'AI Evaluator v2.1',
		sourceCampaignName: 'Q2 Sales Performance',
		sourceInteractionRef: 'CALL-2026-07-010',
		resultingEvaluatorType: 'HUMAN',
		resultingFormName: 'Compliance (Corrected)',
		resultingAgentName: 'Christopher Davis',
		resultingEvaluatorAgentName: null,
		resultingEvaluatorUserName: 'John Smith',
		resultingCampaignName: 'Q2 Sales Performance',
		resultingInteractionRef: 'CALL-2026-07-010',
		disputedByUserId: 202,
		disputedByUserName: 'Maria Garcia',
		reason:
			'Regulatory notification was provided in writing post-call, which meets requirements and is standard practice for this scenario.',
		before: {
			overallScore: 66,
			overallScorePct: 66,
			maxScore: 100,
		},
		after: {
			overallScore: 81,
			overallScorePct: 81,
			maxScore: 100,
		},
		scoreDelta: 15,
		resultingVersion: 2,
		createdAt: '2026-07-19T12:00:00Z',
		status: 'approved',
	},
];

export function getMockDisputes(
	offset = 0,
	limit = 25
): PaginatedResponse<EvaluationDisputeSummary> {
	const start = offset;
	const end = offset + limit;
	const data = mockDisputes.slice(start, end);

	return {
		data,
		total: mockDisputes.length,
	};
}

export function getMockDisputeById(
	disputeId: number
): EvaluationDisputeSummary | undefined {
	return mockDisputes.find((dispute) => dispute.id === disputeId);
}
