import type { EvaluationGroup } from '../DemoCreateQaTestPage/types';

export type DemoQaFormStatus = 'Ready' | 'Draft';

export interface DemoQaForm {
	id: string;
	testName: string;
	qaType: string;
	createdDate: string;
	status: DemoQaFormStatus;
	createdBy: string;
	groups: EvaluationGroup[];
}

export const DEMO_QA_FORMS: DemoQaForm[] = [
	{
		id: 'form-1',
		testName: 'Sales Call Quality Standards',
		qaType: 'Sales',
		createdDate: '2026-06-15',
		status: 'Ready',
		createdBy: 'John Smith',
		groups: [
			{
				id: 'group-1',
				name: 'Greeting & Opening',
				description: 'How the agent opens the conversation',
				items: [
					{
						id: 'item-1',
						name: 'Timely Greeting',
						description: 'Agent greeted within 5 seconds',
						severity: 'Client Critical',
						answerType: 'yesNo',
						yesPoints: 15,
						noPoints: 0,
						naPoints: 0,
						autoFail: false,
						triggerAnswer: 'Yes',
						generalAutoFail: false,
					},
					{
						id: 'item-2',
						name: 'Professional Tone',
						description: 'Used professional tone',
						severity: 'Business Critical',
						answerType: 'yesNo',
						yesPoints: 10,
						noPoints: 0,
						naPoints: 0,
						autoFail: false,
						triggerAnswer: 'Yes',
						generalAutoFail: false,
					},
				],
			},
			{
				id: 'group-2',
				name: 'Sales Pitch',
				description: 'Quality of product presentation',
				items: [
					{
						id: 'item-3',
						name: 'Feature Explanation',
						description: 'Clearly explained features',
						severity: 'Business Critical',
						answerType: 'yesNo',
						yesPoints: 35,
						noPoints: 0,
						naPoints: 0,
						autoFail: false,
						triggerAnswer: 'Yes',
						generalAutoFail: false,
					},
					{
						id: 'item-4',
						name: 'Objection Handling',
						description: 'Addressed customer concerns',
						severity: 'Client Critical',
						answerType: 'yesNo',
						yesPoints: 40,
						noPoints: 0,
						naPoints: 0,
						autoFail: false,
						triggerAnswer: 'Yes',
						generalAutoFail: false,
					},
				],
			},
		],
	},
	{
		id: 'form-2',
		testName: 'Product Description Accuracy',
		qaType: 'Localization',
		createdDate: '2026-06-10',
		status: 'Draft',
		createdBy: 'Maria Garcia',
		groups: [
			{
				id: 'group-3',
				name: 'Translation Quality',
				description: 'Accuracy of translations',
				items: [
					{
						id: 'item-5',
						name: 'Spelling',
						description: 'No spelling errors',
						severity: 'Compliance Critical',
						answerType: 'yesNo',
						yesPoints: 30,
						noPoints: 0,
						naPoints: 0,
						autoFail: true,
						triggerAnswer: 'No',
						generalAutoFail: false,
					},
					{
						id: 'item-6',
						name: 'Terminology',
						description: 'Proper terminology used',
						severity: 'Business Critical',
						answerType: 'yesNo',
						yesPoints: 40,
						noPoints: 0,
						naPoints: 0,
						autoFail: false,
						triggerAnswer: 'Yes',
						generalAutoFail: false,
					},
					{
						id: 'item-7',
						name: 'Phrasing',
						description: 'Natural phrasing',
						severity: 'Business Critical',
						answerType: 'yesNo',
						yesPoints: 30,
						noPoints: 0,
						naPoints: 0,
						autoFail: false,
						triggerAnswer: 'Yes',
						generalAutoFail: false,
					},
				],
			},
		],
	},
	{
		id: 'form-3',
		testName: 'Customer Retention Messaging',
		qaType: 'Retention',
		createdDate: '2026-06-08',
		status: 'Ready',
		createdBy: 'Sarah Johnson',
		groups: [
			{
				id: 'group-4',
				name: 'Message Delivery',
				description: 'How retention message is communicated',
				items: [
					{
						id: 'item-8',
						name: 'Personalization',
						description: 'Message was personalized',
						severity: 'Client Critical',
						answerType: 'yesNo',
						yesPoints: 25,
						noPoints: 0,
						naPoints: 0,
						autoFail: false,
						triggerAnswer: 'Yes',
						generalAutoFail: false,
					},
					{
						id: 'item-9',
						name: 'Offer Relevance',
						description: 'Offer was compelling',
						severity: 'Business Critical',
						answerType: 'yesNo',
						yesPoints: 40,
						noPoints: 0,
						naPoints: 0,
						autoFail: false,
						triggerAnswer: 'Yes',
						generalAutoFail: false,
					},
					{
						id: 'item-10',
						name: 'Call to Action',
						description: 'Call to action was clear',
						severity: 'Business Critical',
						answerType: 'yesNo',
						yesPoints: 35,
						noPoints: 0,
						naPoints: 0,
						autoFail: false,
						triggerAnswer: 'Yes',
						generalAutoFail: false,
					},
				],
			},
		],
	},
	{
		id: 'form-4',
		testName: 'New User Activation Flow',
		qaType: 'Activation',
		createdDate: '2026-06-05',
		status: 'Ready',
		createdBy: 'Michael Chen',
		groups: [
			{
				id: 'group-5',
				name: 'Setup Guidance',
				description: 'Quality of user onboarding assistance',
				items: [
					{
						id: 'item-11',
						name: 'Clear Instructions',
						description: 'Steps explained clearly',
						severity: 'Client Critical',
						answerType: 'yesNo',
						yesPoints: 50,
						noPoints: 0,
						naPoints: 0,
						autoFail: false,
						triggerAnswer: 'Yes',
						generalAutoFail: false,
					},
					{
						id: 'item-12',
						name: 'Confirmation',
						description: 'User confirmed understanding',
						severity: 'Business Critical',
						answerType: 'yesNo',
						yesPoints: 50,
						noPoints: 0,
						naPoints: 0,
						autoFail: false,
						triggerAnswer: 'Yes',
						generalAutoFail: false,
					},
				],
			},
		],
	},
	{
		id: 'form-5',
		testName: 'Invoice Accuracy & Compliance',
		qaType: 'Accounts Receivable',
		createdDate: '2026-05-28',
		status: 'Draft',
		createdBy: 'Amanda Wilson',
		groups: [
			{
				id: 'group-6',
				name: 'Invoice Details',
				description: 'Accuracy of invoice information',
				items: [
					{
						id: 'item-13',
						name: 'Amount Accuracy',
						description: 'All amounts correct',
						severity: 'Compliance Critical',
						answerType: 'yesNo',
						yesPoints: 40,
						noPoints: 0,
						naPoints: 0,
						autoFail: true,
						triggerAnswer: 'No',
						generalAutoFail: false,
					},
					{
						id: 'item-14',
						name: 'Date Accuracy',
						description: 'Dates are accurate',
						severity: 'Business Critical',
						answerType: 'yesNo',
						yesPoints: 30,
						noPoints: 0,
						naPoints: 0,
						autoFail: false,
						triggerAnswer: 'Yes',
						generalAutoFail: false,
					},
					{
						id: 'item-15',
						name: 'Compliance',
						description: 'Compliant with regulations',
						severity: 'Compliance Critical',
						answerType: 'yesNo',
						yesPoints: 30,
						noPoints: 0,
						naPoints: 0,
						autoFail: true,
						triggerAnswer: 'No',
						generalAutoFail: false,
					},
				],
			},
		],
	},
	{
		id: 'form-6',
		testName: 'Multi-language Support Testing',
		qaType: 'Localization',
		createdDate: '2026-05-20',
		status: 'Ready',
		createdBy: 'James Rodriguez',
		groups: [
			{
				id: 'group-7',
				name: 'Language Support',
				description: 'Quality of language support',
				items: [
					{
						id: 'item-16',
						name: 'Language Coverage',
						description: 'All languages tested',
						severity: 'Business Critical',
						answerType: 'yesNo',
						yesPoints: 50,
						noPoints: 0,
						naPoints: 0,
						autoFail: false,
						triggerAnswer: 'Yes',
						generalAutoFail: false,
					},
					{
						id: 'item-17',
						name: 'Encoding',
						description: 'No encoding issues',
						severity: 'Client Critical',
						answerType: 'yesNo',
						yesPoints: 50,
						noPoints: 0,
						naPoints: 0,
						autoFail: false,
						triggerAnswer: 'Yes',
						generalAutoFail: false,
					},
				],
			},
		],
	},
	{
		id: 'form-7',
		testName: 'Regulatory & Legal Compliance Audit',
		qaType: 'Compliance',
		createdDate: '2026-07-15',
		status: 'Ready',
		createdBy: 'Lisa Anderson',
		groups: [
			{
				id: 'group-8',
				name: 'Compliance Checks',
				description: 'Regulatory compliance verification',
				items: [
					{
						id: 'item-18',
						name: 'Document Review',
						description: 'All documents reviewed',
						severity: 'Compliance Critical',
						answerType: 'yesNo',
						yesPoints: 40,
						noPoints: 0,
						naPoints: 0,
						autoFail: false,
						triggerAnswer: 'Yes',
						generalAutoFail: false,
					},
					{
						id: 'item-19',
						name: 'Violations',
						description: 'No violations found',
						severity: 'Compliance Critical',
						answerType: 'yesNo',
						yesPoints: 60,
						noPoints: 0,
						naPoints: 0,
						autoFail: true,
						triggerAnswer: 'No',
						generalAutoFail: false,
					},
				],
			},
		],
	},
];
