import type { DemoAgentCall } from '../../evaluations-demo/AgentDashboard/types';

// Extended mock agent calls with better distribution across agents and dates
export const AGENT_DETAIL_CALLS: DemoAgentCall[] = [
	// Agent 1 calls (Higher performer)
	{
		id: 'agent-1-call-1',
		callDate: '2026-07-28',
		campaign: 'Sales',
		agentName: 'Agent 1',
		durationSeconds: 480,
		score: 95,
		result: 'passed',
		disputed: false,
		evaluationType: 'QA',
		transcript: [],
		evaluationDetails: [
			{
				section: 'Communication',
				items: [
					{ name: 'Clarity', score: 10, maxPoints: 10 },
					{ name: 'Professionalism', score: 10, maxPoints: 10 },
				],
			},
		],
	},
	{
		id: 'agent-1-call-2',
		callDate: '2026-07-29',
		campaign: 'Customer Support',
		agentName: 'Agent 1',
		durationSeconds: 420,
		score: 92,
		result: 'passed',
		disputed: false,
		evaluationType: 'Sentiment Analysis',
		transcript: [],
		evaluationDetails: [],
	},
	{
		id: 'agent-1-call-3',
		callDate: '2026-07-30',
		campaign: 'Retention',
		agentName: 'Agent 1',
		durationSeconds: 540,
		score: 88,
		result: 'passed',
		disputed: false,
		evaluationType: 'Compliance',
		transcript: [],
		evaluationDetails: [],
	},
	{
		id: 'agent-1-call-4',
		callDate: '2026-07-31',
		campaign: 'Sales',
		agentName: 'Agent 1',
		durationSeconds: 360,
		score: 93,
		result: 'passed',
		disputed: false,
		evaluationType: 'QA',
		transcript: [],
		evaluationDetails: [],
	},
	{
		id: 'agent-1-call-5',
		callDate: '2026-08-01',
		campaign: 'Customer Support',
		agentName: 'Agent 1',
		durationSeconds: 450,
		score: 90,
		result: 'passed',
		disputed: false,
		evaluationType: 'Sentiment Analysis',
		transcript: [],
		evaluationDetails: [],
	},
	{
		id: 'agent-1-call-6',
		callDate: '2026-08-02',
		campaign: 'Sales',
		agentName: 'Agent 1',
		durationSeconds: 500,
		score: 94,
		result: 'passed',
		disputed: false,
		evaluationType: 'Compliance',
		transcript: [],
		evaluationDetails: [],
	},

	// Agent 2 calls (Moderate performer)
	{
		id: 'agent-2-call-1',
		callDate: '2026-07-28',
		campaign: 'Retention',
		agentName: 'Agent 2',
		durationSeconds: 600,
		score: 78,
		result: 'passed',
		disputed: false,
		evaluationType: 'QA',
		transcript: [],
		evaluationDetails: [],
	},
	{
		id: 'agent-2-call-2',
		callDate: '2026-07-29',
		campaign: 'Customer Support',
		agentName: 'Agent 2',
		durationSeconds: 480,
		score: 75,
		result: 'passed',
		disputed: false,
		evaluationType: 'Sentiment Analysis',
		transcript: [],
		evaluationDetails: [],
	},
	{
		id: 'agent-2-call-3',
		callDate: '2026-07-30',
		campaign: 'Sales',
		agentName: 'Agent 2',
		durationSeconds: 420,
		score: 80,
		result: 'passed',
		disputed: false,
		evaluationType: 'Compliance',
		transcript: [],
		evaluationDetails: [],
	},
	{
		id: 'agent-2-call-4',
		callDate: '2026-07-31',
		campaign: 'Customer Support',
		agentName: 'Agent 2',
		durationSeconds: 540,
		score: 82,
		result: 'passed',
		disputed: false,
		evaluationType: 'QA',
		transcript: [],
		evaluationDetails: [],
	},
	{
		id: 'agent-2-call-5',
		callDate: '2026-08-01',
		campaign: 'Retention',
		agentName: 'Agent 2',
		durationSeconds: 500,
		score: 77,
		result: 'passed',
		disputed: false,
		evaluationType: 'Sentiment Analysis',
		transcript: [],
		evaluationDetails: [],
	},
	{
		id: 'agent-2-call-6',
		callDate: '2026-08-02',
		campaign: 'Sales',
		agentName: 'Agent 2',
		durationSeconds: 380,
		score: 79,
		result: 'passed',
		disputed: false,
		evaluationType: 'Compliance',
		transcript: [],
		evaluationDetails: [],
	},

	// Agent 3 calls (Lower performer)
	{
		id: 'agent-3-call-1',
		callDate: '2026-07-28',
		campaign: 'Customer Support',
		agentName: 'Agent 3',
		durationSeconds: 720,
		score: 65,
		result: 'failed',
		disputed: false,
		evaluationType: 'QA',
		transcript: [],
		evaluationDetails: [],
	},
	{
		id: 'agent-3-call-2',
		callDate: '2026-07-29',
		campaign: 'Sales',
		agentName: 'Agent 3',
		durationSeconds: 600,
		score: 62,
		result: 'failed',
		disputed: false,
		evaluationType: 'Sentiment Analysis',
		transcript: [],
		evaluationDetails: [],
	},
	{
		id: 'agent-3-call-3',
		callDate: '2026-07-30',
		campaign: 'Retention',
		agentName: 'Agent 3',
		durationSeconds: 500,
		score: 68,
		result: 'failed',
		disputed: false,
		evaluationType: 'Compliance',
		transcript: [],
		evaluationDetails: [],
	},
	{
		id: 'agent-3-call-4',
		callDate: '2026-07-31',
		campaign: 'Customer Support',
		agentName: 'Agent 3',
		durationSeconds: 640,
		score: 70,
		result: 'failed',
		disputed: true,
		evaluationType: 'QA',
		transcript: [],
		evaluationDetails: [],
	},
	{
		id: 'agent-3-call-5',
		callDate: '2026-08-01',
		campaign: 'Sales',
		agentName: 'Agent 3',
		durationSeconds: 560,
		score: 67,
		result: 'failed',
		disputed: false,
		evaluationType: 'Sentiment Analysis',
		transcript: [],
		evaluationDetails: [],
	},
	{
		id: 'agent-3-call-6',
		callDate: '2026-08-02',
		campaign: 'Retention',
		agentName: 'Agent 3',
		durationSeconds: 480,
		score: 64,
		result: 'failed',
		disputed: false,
		evaluationType: 'Compliance',
		transcript: [],
		evaluationDetails: [],
	},

	// Agent 4 calls (High performer)
	{
		id: 'agent-4-call-1',
		callDate: '2026-07-28',
		campaign: 'Sales',
		agentName: 'Agent 4',
		durationSeconds: 400,
		score: 91,
		result: 'passed',
		disputed: false,
		evaluationType: 'QA',
		transcript: [],
		evaluationDetails: [],
	},
	{
		id: 'agent-4-call-2',
		callDate: '2026-07-29',
		campaign: 'Customer Support',
		agentName: 'Agent 4',
		durationSeconds: 440,
		score: 89,
		result: 'passed',
		disputed: false,
		evaluationType: 'Sentiment Analysis',
		transcript: [],
		evaluationDetails: [],
	},
	{
		id: 'agent-4-call-3',
		callDate: '2026-07-30',
		campaign: 'Retention',
		agentName: 'Agent 4',
		durationSeconds: 520,
		score: 87,
		result: 'passed',
		disputed: false,
		evaluationType: 'Compliance',
		transcript: [],
		evaluationDetails: [],
	},
	{
		id: 'agent-4-call-4',
		callDate: '2026-07-31',
		campaign: 'Sales',
		agentName: 'Agent 4',
		durationSeconds: 380,
		score: 92,
		result: 'passed',
		disputed: false,
		evaluationType: 'QA',
		transcript: [],
		evaluationDetails: [],
	},
	{
		id: 'agent-4-call-5',
		callDate: '2026-08-01',
		campaign: 'Customer Support',
		agentName: 'Agent 4',
		durationSeconds: 460,
		score: 88,
		result: 'passed',
		disputed: false,
		evaluationType: 'Sentiment Analysis',
		transcript: [],
		evaluationDetails: [],
	},
	{
		id: 'agent-4-call-6',
		callDate: '2026-08-02',
		campaign: 'Retention',
		agentName: 'Agent 4',
		durationSeconds: 510,
		score: 90,
		result: 'passed',
		disputed: false,
		evaluationType: 'Compliance',
		transcript: [],
		evaluationDetails: [],
	},

	// Agent 5 calls (Needs improvement)
	{
		id: 'agent-5-call-1',
		callDate: '2026-07-28',
		campaign: 'Retention',
		agentName: 'Agent 5',
		durationSeconds: 680,
		score: 72,
		result: 'passed',
		disputed: false,
		evaluationType: 'QA',
		transcript: [],
		evaluationDetails: [],
	},
	{
		id: 'agent-5-call-2',
		callDate: '2026-07-29',
		campaign: 'Sales',
		agentName: 'Agent 5',
		durationSeconds: 600,
		score: 68,
		result: 'failed',
		disputed: false,
		evaluationType: 'Sentiment Analysis',
		transcript: [],
		evaluationDetails: [],
	},
	{
		id: 'agent-5-call-3',
		callDate: '2026-07-30',
		campaign: 'Customer Support',
		agentName: 'Agent 5',
		durationSeconds: 520,
		score: 74,
		result: 'passed',
		disputed: false,
		evaluationType: 'Compliance',
		transcript: [],
		evaluationDetails: [],
	},
	{
		id: 'agent-5-call-4',
		callDate: '2026-07-31',
		campaign: 'Sales',
		agentName: 'Agent 5',
		durationSeconds: 560,
		score: 70,
		result: 'failed',
		disputed: true,
		evaluationType: 'QA',
		transcript: [],
		evaluationDetails: [],
	},
	{
		id: 'agent-5-call-5',
		callDate: '2026-08-01',
		campaign: 'Retention',
		agentName: 'Agent 5',
		durationSeconds: 480,
		score: 71,
		result: 'passed',
		disputed: false,
		evaluationType: 'Sentiment Analysis',
		transcript: [],
		evaluationDetails: [],
	},
	{
		id: 'agent-5-call-6',
		callDate: '2026-08-02',
		campaign: 'Customer Support',
		agentName: 'Agent 5',
		durationSeconds: 440,
		score: 69,
		result: 'failed',
		disputed: false,
		evaluationType: 'Compliance',
		transcript: [],
		evaluationDetails: [],
	},
];

// Agent performance summary data
export const AGENT_PERFORMANCE_DATA = {
	'Agent 1': {
		satisfactionRate: 92,
		bestDay: 'Tuesday',
		bestHour: '10:00 AM - 11:00 AM',
		avgHandleTime: '5m 30s',
		dominantSentiment: 'Very Positive',
		totalCalls: 6,
		campaignPerformance: {
			Sales: 'Excellent',
			Retention: 'Excellent',
			'Customer Support': 'Very Good',
		},
		supervisor: 'John Manager',
	},
	'Agent 2': {
		satisfactionRate: 78,
		bestDay: 'Wednesday',
		bestHour: '02:00 PM - 03:00 PM',
		avgHandleTime: '8m 15s',
		dominantSentiment: 'Neutral',
		totalCalls: 6,
		campaignPerformance: {
			Sales: 'Good',
			Retention: 'Fair',
			'Customer Support': 'Good',
		},
		supervisor: 'John Manager',
	},
	'Agent 3': {
		satisfactionRate: 66,
		bestDay: 'Friday',
		bestHour: '11:00 AM - 12:00 PM',
		avgHandleTime: '10m 45s',
		dominantSentiment: 'Slightly Negative',
		totalCalls: 6,
		campaignPerformance: {
			Sales: 'Fair',
			Retention: 'Fair',
			'Customer Support': 'Needs Improvement',
		},
		supervisor: 'Sarah Supervisor',
	},
	'Agent 4': {
		satisfactionRate: 89,
		bestDay: 'Monday',
		bestHour: '09:00 AM - 10:00 AM',
		avgHandleTime: '6m 30s',
		dominantSentiment: 'Positive',
		totalCalls: 6,
		campaignPerformance: {
			Sales: 'Excellent',
			Retention: 'Very Good',
			'Customer Support': 'Very Good',
		},
		supervisor: 'Sarah Supervisor',
	},
	'Agent 5': {
		satisfactionRate: 71,
		bestDay: 'Thursday',
		bestHour: '03:00 PM - 04:00 PM',
		avgHandleTime: '9m 20s',
		dominantSentiment: 'Neutral',
		totalCalls: 6,
		campaignPerformance: {
			Sales: 'Fair',
			Retention: 'Good',
			'Customer Support': 'Fair',
		},
		supervisor: 'John Manager',
	},
};
