export const mockRiskAlerts = [
	{
		id: 'alert-1',
		type: 'compliance' as const,
		title: 'Compliance Breaches This Week',
		count: 12,
		severity: 'high' as const,
		description: 'Policy violations detected in QA audit evaluations',
		affectedSupervisors: ['Sarah Chen', 'Michael Torres'],
	},
	{
		id: 'alert-2',
		type: 'sentiment' as const,
		title: 'Negative Sentiment Escalations',
		count: 8,
		severity: 'high' as const,
		description: 'Clients and agents showing downward sentiment trend',
		affectedSupervisors: ['James Wilson'],
	},
	{
		id: 'alert-3',
		type: 'trend' as const,
		title: 'Downtrending Agents',
		count: 5,
		severity: 'medium' as const,
		description: 'Performance declining week-over-week despite supervision',
		affectedSupervisors: ['Sarah Chen', 'Marcus Johnson'],
	},
];

export const mockDashboardKPIs = {
	generalQAScore: 87,
	generalEmotionSentimentScore: 81,
	complianceScore: 87,
};

export const mockSupervisors = [
	{
		id: 'sup-1',
		name: 'Sarah Chen',
		teamSize: 12,
		complianceAdherence: 88,
		emotionScore: 8.2,
		sentimentScore: 7.9,
		uptrendingAgentsPercent: 75,
		qaAnalysisScore: 82,
		avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Sarah',
		status: 'caution' as const,
	},
	{
		id: 'sup-2',
		name: 'Marcus Johnson',
		teamSize: 15,
		complianceAdherence: 94,
		emotionScore: 8.7,
		sentimentScore: 8.5,
		uptrendingAgentsPercent: 87,
		qaAnalysisScore: 91,
		avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Marcus',
		status: 'strong' as const,
	},
	{
		id: 'sup-3',
		name: 'James Wilson',
		teamSize: 10,
		complianceAdherence: 72,
		emotionScore: 7.1,
		sentimentScore: 6.8,
		uptrendingAgentsPercent: 60,
		qaAnalysisScore: 68,
		avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=James',
		status: 'at-risk' as const,
	},
	{
		id: 'sup-4',
		name: 'Elena Rodriguez',
		teamSize: 14,
		complianceAdherence: 92,
		emotionScore: 8.5,
		sentimentScore: 8.3,
		uptrendingAgentsPercent: 84,
		qaAnalysisScore: 89,
		avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Elena',
		status: 'strong' as const,
	},
	{
		id: 'sup-5',
		name: 'Michael Torres',
		teamSize: 13,
		complianceAdherence: 81,
		emotionScore: 7.8,
		sentimentScore: 7.6,
		uptrendingAgentsPercent: 70,
		qaAnalysisScore: 79,
		avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Michael',
		status: 'caution' as const,
	},
];

export const mockQAAnalytics = {
	kpi: {
		compliance: 87,
		emotion: 8.3,
		sentiment: 8.1,
	},
	supervisors: [
		{
			id: 'sup-1',
			name: 'Sarah Chen',
			compliance: 88,
			emotion: 8.2,
			sentiment: 7.9,
			trend: [
				{ week: 'W1', value: 85 },
				{ week: 'W2', value: 86 },
				{ week: 'W3', value: 87 },
				{ week: 'W4', value: 88 },
			],
		},
		{
			id: 'sup-2',
			name: 'Marcus Johnson',
			compliance: 94,
			emotion: 8.7,
			sentiment: 8.5,
			trend: [
				{ week: 'W1', value: 92 },
				{ week: 'W2', value: 93 },
				{ week: 'W3', value: 93 },
				{ week: 'W4', value: 94 },
			],
		},
		{
			id: 'sup-3',
			name: 'James Wilson',
			compliance: 72,
			emotion: 7.1,
			sentiment: 6.8,
			trend: [
				{ week: 'W1', value: 78 },
				{ week: 'W2', value: 75 },
				{ week: 'W3', value: 73 },
				{ week: 'W4', value: 72 },
			],
		},
		{
			id: 'sup-4',
			name: 'Elena Rodriguez',
			compliance: 92,
			emotion: 8.5,
			sentiment: 8.3,
			trend: [
				{ week: 'W1', value: 90 },
				{ week: 'W2', value: 91 },
				{ week: 'W3', value: 92 },
				{ week: 'W4', value: 92 },
			],
		},
		{
			id: 'sup-5',
			name: 'Michael Torres',
			compliance: 81,
			emotion: 7.8,
			sentiment: 7.6,
			trend: [
				{ week: 'W1', value: 79 },
				{ week: 'W2', value: 80 },
				{ week: 'W3', value: 81 },
				{ week: 'W4', value: 81 },
			],
		},
	],
	campaigns: [
		{
			id: 'camp-1',
			name: 'Billing Support Q3',
			compliance: 79,
			emotion: 7.8,
			sentiment: 7.5,
			affectedSupervisors: ['Sarah Chen', 'James Wilson'],
			trend: [
				{ week: 'W1', value: 75 },
				{ week: 'W2', value: 77 },
				{ week: 'W3', value: 78 },
				{ week: 'W4', value: 79 },
			],
		},
		{
			id: 'camp-2',
			name: 'Technical Support',
			compliance: 91,
			emotion: 8.6,
			sentiment: 8.4,
			affectedSupervisors: ['Marcus Johnson', 'Elena Rodriguez'],
			trend: [
				{ week: 'W1', value: 89 },
				{ week: 'W2', value: 90 },
				{ week: 'W3', value: 91 },
				{ week: 'W4', value: 91 },
			],
		},
		{
			id: 'camp-3',
			name: 'General Inquiries',
			compliance: 88,
			emotion: 8.2,
			sentiment: 8.0,
			affectedSupervisors: ['Michael Torres', 'Sarah Chen'],
			trend: [
				{ week: 'W1', value: 86 },
				{ week: 'W2', value: 87 },
				{ week: 'W3', value: 88 },
				{ week: 'W4', value: 88 },
			],
		},
		{
			id: 'camp-4',
			name: 'VIP Account Services',
			compliance: 95,
			emotion: 8.9,
			sentiment: 8.8,
			affectedSupervisors: ['Elena Rodriguez'],
			trend: [
				{ week: 'W1', value: 94 },
				{ week: 'W2', value: 94 },
				{ week: 'W3', value: 95 },
				{ week: 'W4', value: 95 },
			],
		},
	],
};

export const mockDisputes = [
	{
		id: 'dispute-1',
		agentId: 'AG-001',
		agentName: 'John Smith',
		evaluationScore: 78,
		evaluationDate: '2024-08-12',
		submittedDate: '2024-08-14',
		status: 'pending' as const,
		reason: 'Score is too low, call quality was better',
	},
	{
		id: 'dispute-2',
		agentId: 'AG-015',
		agentName: 'Sarah Johnson',
		evaluationScore: 85,
		evaluationDate: '2024-08-11',
		submittedDate: '2024-08-13',
		status: 'pending' as const,
		reason: 'Disagree with compliance breach marking',
	},
	{
		id: 'dispute-3',
		agentId: 'AG-008',
		agentName: 'Mike Chen',
		evaluationScore: 92,
		evaluationDate: '2024-08-10',
		submittedDate: '2024-08-12',
		status: 'in-review' as const,
		reason: 'Emotion score calculation error',
	},
	{
		id: 'dispute-4',
		agentId: 'AG-022',
		agentName: 'Emma Davis',
		evaluationScore: 71,
		evaluationDate: '2024-08-09',
		submittedDate: '2024-08-11',
		status: 'pending' as const,
		reason: 'Supervisor scoring inconsistency',
	},
	{
		id: 'dispute-5',
		agentId: 'AG-031',
		agentName: 'Robert Martinez',
		evaluationScore: 88,
		evaluationDate: '2024-08-08',
		submittedDate: '2024-08-10',
		status: 'resolved' as const,
		reason: 'Score adjusted after review',
	},
];

export const mockCampaignPerformance = [
	{
		id: 'camp-1',
		name: 'VIP Account Services',
		callVolume: 2845,
		complianceViolations: 3,
		performance: 'best' as const,
	},
	{
		id: 'camp-2',
		name: 'Technical Support',
		callVolume: 2156,
		complianceViolations: 8,
		performance: 'best' as const,
	},
	{
		id: 'camp-3',
		name: 'General Inquiries',
		callVolume: 1923,
		complianceViolations: 12,
		performance: 'best' as const,
	},
	{
		id: 'camp-4',
		name: 'Billing Support Q3',
		callVolume: 1245,
		complianceViolations: 31,
		performance: 'lowest' as const,
	},
	{
		id: 'camp-5',
		name: 'Collections Campaign',
		callVolume: 1089,
		complianceViolations: 42,
		performance: 'lowest' as const,
	},
	{
		id: 'camp-6',
		name: 'Renewal Outreach',
		callVolume: 987,
		complianceViolations: 28,
		performance: 'lowest' as const,
	},
];

export const mockSentimentMetrics = {
	agentSentimentScore: 8.3,
	clientSentimentScore: 8.1,
};

export const mockQAIssuesSummary = [
	{
		category: 'Billing Policy Violations',
		count: 12,
		trend: 'up' as const,
	},
	{
		category: 'Negative Sentiment Escalations',
		count: 8,
		trend: 'down' as const,
	},
	{
		category: 'Documentation Gaps',
		count: 6,
		trend: 'stable' as const,
	},
];

export const mockAuditQueue = {
	pendingAudits: [
		{
			id: 'audit-1',
			callId: 'CALL-2024-0891',
			supervisor: 'Sarah Chen',
			complianceRisk: 'high',
			ageInDays: 2,
			status: 'pending' as const,
		},
		{
			id: 'audit-2',
			callId: 'CALL-2024-0892',
			supervisor: 'James Wilson',
			complianceRisk: 'high',
			ageInDays: 1,
			status: 'pending' as const,
		},
		{
			id: 'audit-3',
			callId: 'CALL-2024-0893',
			supervisor: 'Michael Torres',
			complianceRisk: 'medium',
			ageInDays: 3,
			status: 'in-progress' as const,
		},
		{
			id: 'audit-4',
			callId: 'CALL-2024-0894',
			supervisor: 'Sarah Chen',
			complianceRisk: 'medium',
			ageInDays: 2,
			status: 'pending' as const,
		},
		{
			id: 'audit-5',
			callId: 'CALL-2024-0895',
			supervisor: 'Elena Rodriguez',
			complianceRisk: 'low',
			ageInDays: 4,
			status: 'pending' as const,
		},
		{
			id: 'audit-6',
			callId: 'CALL-2024-0896',
			supervisor: 'Marcus Johnson',
			complianceRisk: 'low',
			ageInDays: 5,
			status: 'in-progress' as const,
		},
		{
			id: 'audit-7',
			callId: 'CALL-2024-0897',
			supervisor: 'James Wilson',
			complianceRisk: 'high',
			ageInDays: 1,
			status: 'pending' as const,
		},
		{
			id: 'audit-8',
			callId: 'CALL-2024-0898',
			supervisor: 'Michael Torres',
			complianceRisk: 'medium',
			ageInDays: 2,
			status: 'pending' as const,
		},
		{
			id: 'audit-9',
			callId: 'CALL-2024-0899',
			supervisor: 'Sarah Chen',
			complianceRisk: 'high',
			ageInDays: 3,
			status: 'pending' as const,
		},
		{
			id: 'audit-10',
			callId: 'CALL-2024-0900',
			supervisor: 'Elena Rodriguez',
			complianceRisk: 'low',
			ageInDays: 6,
			status: 'completed' as const,
		},
	],
	findings: [
		{
			id: 'finding-1',
			category: 'Billing Policy Violations',
			issueCount: 12,
			trend: 'up' as const,
			affectedSupervisors: ['Sarah Chen', 'James Wilson'],
			coachingRecommendation:
				'Schedule coaching on billing disclosure requirements. Focus on verifying fee transparency before call completion.',
		},
		{
			id: 'finding-2',
			category: 'Negative Sentiment Escalations',
			issueCount: 8,
			trend: 'down' as const,
			affectedSupervisors: ['James Wilson'],
			coachingRecommendation:
				'Review de-escalation techniques. Agent frustration levels increasing; consider peer mentoring with Marcus Johnson.',
		},
		{
			id: 'finding-3',
			category: 'Documentation Gaps',
			issueCount: 6,
			trend: 'stable' as const,
			affectedSupervisors: ['Michael Torres'],
			coachingRecommendation:
				'Ensure all call notes are completed before supervisor sign-off. Implement call review checklist.',
		},
		{
			id: 'finding-4',
			category: 'Compliance Training Needed',
			issueCount: 4,
			trend: 'down' as const,
			affectedSupervisors: ['Sarah Chen'],
			coachingRecommendation:
				'Schedule compliance refresher training. Recent audit shows improvement; continue current approach.',
		},
	],
};
