/**
 * Maps QA route ids to the i18n namespaces they need, mirroring
 * campaignNamespaces.ts. Consumed by I18nNamespaceLoader in routes.tsx.
 */
export const qaRouteNamespaces: Record<string, string | readonly string[]> = {
	'qa.dashboard': 'qa.dashboard',
	'qa.agent.rankings': [
		'qa.rankings',
		'qa.teamAnalytics',
		'qa.triggers',
		'qa.team',
	],
	'qa.supervisor.rankings': [
		'qa.rankings',
		'qa.teamAnalytics',
		'qa.triggers',
		'qa.team',
	],
	'qa.qa-manager.rankings': [
		'qa.rankings',
		'qa.teamAnalytics',
		'qa.triggers',
		'qa.team',
	],
	'qa.dashboards.agent': ['qa.dashboard', 'qa.rankings', 'qa.teamAnalytics'],
	'qa.dashboards.supervisor': [
		'qa.dashboard',
		'qa.rankings',
		'qa.teamAnalytics',
	],
	'qa.dashboards.qa-manager': [
		'qa.dashboard',
		'qa.rankings',
		'qa.teamAnalytics',
	],
	'qa.dashboards.operation-manager': [
		'qa.dashboard',
		'qa.rankings',
		'qa.teamAnalytics',
	],
	'qa.agent.inbox': ['qa.inbox', 'qa.teamAnalytics', 'qa.team'],
	'qa.supervisor.inbox': ['qa.inbox', 'qa.teamAnalytics', 'qa.team'],
	'qa.qa-manager.inbox': ['qa.inbox', 'qa.teamAnalytics', 'qa.team'],
	'qa.operation-manager.inbox': ['qa.inbox', 'qa.teamAnalytics', 'qa.team'],
	'qa.supervisor.reports': [
		'qa.reports',
		'qa.teamAnalytics',
		'qa.team',
		'qa.coaching',
		'qa.lms',
		'qa.disputes',
		'qa.rankings',
	],
	'qa.qa-manager.reports': [
		'qa.reports',
		'qa.teamAnalytics',
		'qa.team',
		'qa.coaching',
		'qa.lms',
		'qa.disputes',
		'qa.rankings',
	],
	'qa.agents': 'qa.agents',
	'qa.agents.detail': 'qa.agents',
	'qa.agent.calls': [
		'qa.calls',
		'qa.team',
		'qa.disputes',
		'qa.teamAnalytics',
		'qa.inbox',
	],
	'qa.campaigns': 'qa.campaigns',
	'qa.campaigns.detail': ['qa.campaigns', 'qa.calls', 'qa.team'],
	'qa.campaigns.conversation': ['qa.disputes', 'qa.calls'],
	'qa.forms': 'qa.forms',
	'qa.forms.error-types': 'qa.forms',
	'qa.forms.detail': 'qa.forms',
	'qa.evaluations': 'qa.evaluations',
	'qa.evaluations.new': 'qa.evaluations',
	'qa.evaluations.detail': 'qa.evaluations',
	'qa.emotion-sentiment': 'qa.emotionSentiment',
	'emotion-sentiment': 'qa.emotionSentiment',
	'qa.disputes': 'qa.disputes',
	'qa.agent.disputes': [
		'qa.disputes',
		'qa.team',
		'qa.teamAnalytics',
		'qa.inbox',
	],
	'qa.agent.disputes.detail': [
		'qa.disputes',
		'qa.team',
		'qa.teamAnalytics',
		'qa.inbox',
	],
	'qa.supervisor.disputes': [
		'qa.disputes',
		'qa.team',
		'qa.teamAnalytics',
		'qa.inbox',
	],
	'qa.supervisor.disputes.detail': [
		'qa.disputes',
		'qa.team',
		'qa.teamAnalytics',
		'qa.inbox',
	],
	'qa.qa-manager.disputes': [
		'qa.disputes',
		'qa.team',
		'qa.teamAnalytics',
		'qa.inbox',
	],
	'qa.qa-manager.disputes.detail': [
		'qa.disputes',
		'qa.team',
		'qa.teamAnalytics',
		'qa.inbox',
	],
	'qa.qamanager.disputes': [
		'qa.disputes',
		'qa.team',
		'qa.teamAnalytics',
		'qa.inbox',
	],
	'qa.qamanager.disputes.detail': [
		'qa.disputes',
		'qa.team',
		'qa.teamAnalytics',
		'qa.inbox',
	],
	'qa.disputes.detail': 'qa.disputes',
	'qa.evaluator-agents': 'qa.evaluatorAgents',
	'qa.supervisor.triggers': 'qa.triggers',
	'qa.qa-manager.triggers': 'qa.triggers',
	'qa.agent.lms': ['qa.lms', 'qa.team', 'qa.triggers'],
	'qa.agent.lms.content': ['qa.lms', 'qa.team', 'qa.triggers'],
	'qa.agent.coaching': ['qa.lms', 'qa.team'],
	'qa.supervisor.lms': ['qa.lms', 'qa.team', 'qa.triggers'],
	'qa.qa-manager.lms': ['qa.lms', 'qa.team', 'qa.triggers'],
	'qa.supervisor.coaching': ['qa.coaching', 'qa.lms', 'qa.triggers', 'qa.team'],
	'qa.qa-manager.coaching': ['qa.coaching', 'qa.lms', 'qa.triggers', 'qa.team'],
	'qa.supervisor.your-team': ['qa.team', 'qa.dashboard'],
	'qa.supervisor.your-team.profile': ['qa.team', 'qa.dashboard'],
	'qa.qa-manager.agents': ['qa.team', 'qa.dashboard'],
	'qa.qa-manager.agents.profile': ['qa.team', 'qa.dashboard'],
	'qa.supervisor.customers': ['qa.customers', 'qa.team', 'qa.dashboard'],
	'qa.supervisor.customers.profile': [
		'qa.customers',
		'qa.team',
		'qa.dashboard',
	],
	'qa.qa-manager.customers': ['qa.customers', 'qa.team', 'qa.dashboard'],
	'qa.qa-manager.customers.profile': [
		'qa.customers',
		'qa.team',
		'qa.dashboard',
	],
	'qa.supervisor.analytics': [
		'qa.teamAnalytics',
		'qa.agent.analytics',
		'qa.dashboard',
		'qa.team',
		'qa.lms',
		'qa.coaching',
	],
	'qa.qa-manager.analytics': [
		'qa.teamAnalytics',
		'qa.agent.analytics',
		'qa.dashboard',
		'qa.team',
		'qa.lms',
		'qa.coaching',
	],
};
