import type {
	GeneratedReportRecord,
	ReportDefinition,
} from '~/models/qa/reportBuilder';
import { TODAY, addDays } from '~/modules/qa/analytics/constants';
import {
	QA_MANAGER_PERSONA,
	SUPERVISOR_PERSONA,
} from '~/modules/qa/team/constants';
import { nextRunAt } from './helpers';

const period = (days: number) => ({
	preset:
		days === 7
			? ('7d' as const)
			: days === 30
				? ('30d' as const)
				: ('90d' as const),
	from: addDays(TODAY, -(days - 1)),
	to: TODAY,
	compareWithPrevious: true,
});

const emptyScope = {
	teams: [] as string[],
	supervisorIds: [] as string[],
	agentIds: [] as string[],
	campaignIds: [] as string[],
	linesOfBusiness: [] as string[],
};

export const REPORT_DEFINITIONS_SEED: ReportDefinition[] = [
	{
		id: 'RPT-001',
		name: 'Weekly Quality Report — Acme Retail',
		description:
			'Client-facing weekly summary of quality, compliance, sentiment and conversion for the Acme Retail campaigns.',
		audience: 'client',
		clientName: 'Acme Retail',
		showAgentNames: false,
		period: period(7),
		scope: { ...emptyScope, campaignIds: ['camp-001', 'camp-004'] },
		groupBy: 'campaign',
		sections: ['overview', 'qa', 'compliance', 'sentiment', 'business'],
		metrics: [],
		formats: ['PDF', 'CSV'],
		schedule: {
			enabled: true,
			frequency: 'WEEKLY',
			dayOfWeek: 1,
			time: '08:00',
			recipients: ['ops@acmeretail.com'],
			nextRunAt: nextRunAt('WEEKLY', 1, '08:00'),
		},
		builtIn: true,
		createdBy: QA_MANAGER_PERSONA.name,
		createdByRole: 'QA_MANAGER',
		createdAt: '2026-07-02T09:00:00Z',
		updatedAt: '2026-09-07T08:00:00Z',
		lastGeneratedAt: '2026-09-07T08:00:00Z',
	},
	{
		id: 'RPT-002',
		name: 'Monthly Team Performance',
		description:
			'Everything Team 1 did this month: scores per agent, coaching, learning and the running ranking.',
		audience: 'internal',
		clientName: null,
		showAgentNames: true,
		period: period(30),
		scope: { ...emptyScope, teams: ['Team 1'] },
		groupBy: 'agent',
		sections: [
			'overview',
			'qa',
			'compliance',
			'sentiment',
			'business',
			'agents',
			'coaching',
			'rankings',
		],
		metrics: [],
		formats: ['PDF', 'XLSX'],
		schedule: {
			enabled: true,
			frequency: 'MONTHLY',
			dayOfWeek: 1,
			time: '09:00',
			recipients: ['maria.garcia@company.com'],
			nextRunAt: nextRunAt('MONTHLY', 1, '09:00'),
		},
		builtIn: true,
		createdBy: SUPERVISOR_PERSONA.name,
		createdByRole: 'SUPERVISOR',
		createdAt: '2026-06-01T10:00:00Z',
		updatedAt: '2026-09-01T09:00:00Z',
		lastGeneratedAt: '2026-09-01T09:00:00Z',
	},
	{
		id: 'RPT-003',
		name: 'Compliance Audit Pack',
		description:
			'Quarterly compliance evidence for Northwind Bank, broken down by line of business.',
		audience: 'client',
		clientName: 'Northwind Bank',
		showAgentNames: false,
		period: period(90),
		scope: { ...emptyScope, linesOfBusiness: ['Collections'] },
		groupBy: 'lineOfBusiness',
		sections: ['overview', 'compliance', 'campaigns'],
		metrics: [],
		formats: ['PDF'],
		schedule: null,
		builtIn: true,
		createdBy: QA_MANAGER_PERSONA.name,
		createdByRole: 'QA_MANAGER',
		createdAt: '2026-07-15T11:30:00Z',
		updatedAt: '2026-08-28T16:10:00Z',
		lastGeneratedAt: '2026-08-28T16:10:00Z',
	},
	{
		id: 'RPT-004',
		name: 'Coaching & Wellbeing Review',
		description:
			'Coaching load, burnout signals and disputes across every team, for the operations review.',
		audience: 'internal',
		clientName: null,
		showAgentNames: true,
		period: period(30),
		scope: emptyScope,
		groupBy: 'supervisor',
		sections: ['overview', 'coaching', 'burnout', 'disputes'],
		metrics: [],
		formats: ['PDF', 'CSV'],
		schedule: {
			enabled: true,
			frequency: 'BIWEEKLY',
			dayOfWeek: 5,
			time: '16:00',
			recipients: ['elena.ruiz@company.com', 'operations@company.com'],
			nextRunAt: nextRunAt('BIWEEKLY', 5, '16:00'),
		},
		builtIn: true,
		createdBy: QA_MANAGER_PERSONA.name,
		createdByRole: 'QA_MANAGER',
		createdAt: '2026-08-05T14:00:00Z',
		updatedAt: '2026-09-11T16:00:00Z',
		lastGeneratedAt: '2026-09-11T16:00:00Z',
	},
];

export const GENERATED_REPORTS_SEED: GeneratedReportRecord[] = [
	{
		id: 'GEN-006',
		definitionId: 'RPT-004',
		definitionName: 'Coaching & Wellbeing Review',
		audience: 'internal',
		format: 'PDF',
		generatedAt: '2026-09-11T16:00:00Z',
		trigger: 'SCHEDULED',
		sizeKb: 486,
		status: 'SENT',
		recipients: ['elena.ruiz@company.com', 'operations@company.com'],
	},
	{
		id: 'GEN-005',
		definitionId: 'RPT-001',
		definitionName: 'Weekly Quality Report — Acme Retail',
		audience: 'client',
		format: 'PDF',
		generatedAt: '2026-09-07T08:00:00Z',
		trigger: 'SCHEDULED',
		sizeKb: 312,
		status: 'SENT',
		recipients: ['ops@acmeretail.com'],
	},
	{
		id: 'GEN-004',
		definitionId: 'RPT-002',
		definitionName: 'Monthly Team Performance',
		audience: 'internal',
		format: 'XLSX',
		generatedAt: '2026-09-01T09:00:00Z',
		trigger: 'SCHEDULED',
		sizeKb: 128,
		status: 'SENT',
		recipients: ['maria.garcia@company.com'],
	},
	{
		id: 'GEN-003',
		definitionId: 'RPT-003',
		definitionName: 'Compliance Audit Pack',
		audience: 'client',
		format: 'PDF',
		generatedAt: '2026-08-28T16:10:00Z',
		trigger: 'MANUAL',
		sizeKb: 974,
		status: 'READY',
		recipients: [],
	},
	{
		id: 'GEN-002',
		definitionId: 'RPT-001',
		definitionName: 'Weekly Quality Report — Acme Retail',
		audience: 'client',
		format: 'CSV',
		generatedAt: '2026-08-24T08:00:00Z',
		trigger: 'SCHEDULED',
		sizeKb: 141,
		status: 'SENT',
		recipients: ['ops@acmeretail.com'],
	},
	{
		id: 'GEN-001',
		definitionId: 'RPT-002',
		definitionName: 'Monthly Team Performance',
		audience: 'internal',
		format: 'PDF',
		generatedAt: '2026-08-17T12:42:00Z',
		trigger: 'MANUAL',
		sizeKb: 523,
		status: 'READY',
		recipients: [],
	},
];
