import type { AgentNotification } from '~/models/qa/notifications';
import {
	AGENT_PERSONA_ID,
	QA_MANAGER_PERSONA,
	SUPERVISOR_PERSONA,
} from '~/modules/qa/team/constants';
import { buildNotification } from './helpers';

const day = (d: number, time = '09:00:00') =>
	`2026-09-${String(d).padStart(2, '0')}T${time}Z`;

/** John Smith's inbox — one entry per payload kind so every detail has a demo row. */
const AGENT_INBOX: AgentNotification[] = [
	buildNotification({
		id: 'ntf-a01',
		agentId: AGENT_PERSONA_ID,
		category: 'METRIC_ALERT',
		priority: 'CRITICAL',
		title: 'QA score below target',
		message:
			'Your QA score dropped to 71% over the last 7 days, under the 75% threshold your supervisor set for the team.',
		icon: 'alert-triangle',
		sourceRole: 'SYSTEM',
		metric: 'QUALITY_ASSURANCE',
		createdAt: day(12, '08:15:00'),
		payload: {
			kind: 'METRIC_ALERT',
			area: 'QUALITY_ASSURANCE',
			metricId: 'QA_OVERALL_SCORE',
			value: 71,
			threshold: 75,
			direction: 'BELOW',
			windowLabel: 'Last 7 days',
			sparkline: [82, 80, 78, 76, 74, 72, 71],
			ruleName: 'QA score drop',
		},
	}),
	buildNotification({
		id: 'ntf-a02',
		agentId: AGENT_PERSONA_ID,
		category: 'TREND_WARNING',
		priority: 'HIGH',
		title: 'Customer sentiment is trending down',
		message:
			'Customer sentiment fell from 4.1 to 3.6 over the last two weeks. Most of the drop comes from calls after 17:00.',
		icon: 'trending-down',
		sourceRole: 'SYSTEM',
		metric: 'SENTIMENT_EMOTION',
		createdAt: day(11, '16:40:00'),
		payload: {
			kind: 'TREND_WARNING',
			area: 'SENTIMENT_EMOTION',
			metricId: 'CUSTOMER_SENTIMENT_SCORE',
			from: 4.1,
			to: 3.6,
			deltaPct: -12,
			periodLabel: 'Last 14 days',
			sparkline: [4.1, 4.0, 3.9, 3.9, 3.8, 3.7, 3.6],
			ruleName: 'Sentiment decline',
		},
	}),
	buildNotification({
		id: 'ntf-a03',
		agentId: AGENT_PERSONA_ID,
		category: 'TREND_WARNING',
		priority: 'HIGH',
		title: 'Your burnout risk moved to medium',
		message:
			'Two of the five burnout conditions are met this week. Talk to Maria if the workload feels unsustainable.',
		icon: 'flame',
		sourceRole: 'SYSTEM',
		createdAt: day(11, '07:30:00'),
		payload: {
			kind: 'BURNOUT_RISK',
			level: 'medium',
			percentage: 55,
			drivers: ['negativeEmotionShare', 'qaScoreTrend'],
		},
	}),
	buildNotification({
		id: 'ntf-a04',
		agentId: AGENT_PERSONA_ID,
		category: 'POSITIVE_RECOGNITION',
		priority: 'LOW',
		title: 'Three weeks in the top 3',
		message:
			'You have held a top-3 position in the team ranking for three weeks running. Keep it up.',
		icon: 'trophy',
		sourceRole: 'SUPERVISOR',
		sourceId: SUPERVISOR_PERSONA.id,
		read: true,
		createdAt: day(10, '11:00:00'),
		payload: { kind: 'RECOGNITION', type: 'STREAK', streakWeeks: 3 },
	}),
	buildNotification({
		id: 'ntf-a05',
		agentId: AGENT_PERSONA_ID,
		category: 'POSITIVE_RECOGNITION',
		priority: 'NORMAL',
		title: 'Badge earned: Consistency Streak',
		message: 'Awarded for steady scores across ten consecutive evaluations.',
		icon: 'award',
		sourceRole: 'SYSTEM',
		read: true,
		createdAt: day(9, '10:00:00'),
		payload: {
			kind: 'BADGE_EARNED',
			badgeId: 'BDG-007',
			badgeName: 'Consistency Streak',
			badgeIcon: '🔥',
			badgeColor: 'orange',
			tier: 'SILVER',
			reason: 'Ten consecutive evaluations above target.',
		},
	}),
	buildNotification({
		id: 'ntf-a06',
		agentId: AGENT_PERSONA_ID,
		category: 'WEEKLY_SUMMARY',
		priority: 'LOW',
		title: 'Your week: 1–7 September',
		message:
			'QA held steady, sentiment slipped slightly and conversion improved.',
		icon: 'calendar-stats',
		sourceRole: 'SYSTEM',
		read: true,
		createdAt: day(8, '07:00:00'),
		payload: {
			kind: 'WEEKLY_SUMMARY',
			weekLabel: '1–7 September',
			kpis: [
				{ label: 'QA score', value: '84%', delta: 2 },
				{ label: 'Compliance', value: '92%', delta: 0 },
				{ label: 'Sentiment', value: '3.9', delta: -0.2 },
				{ label: 'Calls', value: '61', delta: 4 },
			],
			highlights: [
				'Best conversion rate of the team on Tuesday.',
				'Two compliance warnings on disclosure wording.',
			],
		},
	}),
	buildNotification({
		id: 'ntf-a07',
		agentId: AGENT_PERSONA_ID,
		category: 'DIRECT_MESSAGE',
		priority: 'NORMAL',
		title: 'Coaching session scheduled',
		message: 'Maria booked a 1:1 to work on objection handling.',
		icon: 'school',
		sourceRole: 'SUPERVISOR',
		sourceId: SUPERVISOR_PERSONA.id,
		createdAt: day(10, '15:20:00'),
		payload: {
			kind: 'COACHING_SESSION',
			sessionId: 'CS-2041',
			date: '2026-09-15T14:00:00Z',
			coachName: SUPERVISOR_PERSONA.name,
			topic: 'Objection handling',
		},
	}),
	buildNotification({
		id: 'ntf-a08',
		agentId: AGENT_PERSONA_ID,
		category: 'DIRECT_MESSAGE',
		priority: 'HIGH',
		title: 'New assignment: Compliance refresher',
		message: 'Mandatory material after the disclosure findings of last week.',
		icon: 'book',
		sourceRole: 'QA_MANAGER',
		sourceId: QA_MANAGER_PERSONA.id,
		createdAt: day(9, '12:10:00'),
		payload: {
			kind: 'LMS_ASSIGNMENT',
			assignmentId: 'LMS-3312',
			contentTitle: 'Compliance refresher',
			dueDate: '2026-09-20',
			mandatory: true,
		},
	}),
	buildNotification({
		id: 'ntf-a09',
		agentId: AGENT_PERSONA_ID,
		category: 'POSITIVE_RECOGNITION',
		priority: 'NORMAL',
		title: 'Your dispute was accepted',
		message:
			'Two items were scored wrongly on call CALL-2031. The QA score was corrected from 71% to 82%.',
		icon: 'flag',
		sourceRole: 'QA_MANAGER',
		sourceId: QA_MANAGER_PERSONA.id,
		read: true,
		createdAt: day(5, '13:45:00'),
		payload: {
			kind: 'DISPUTE_UPDATE',
			disputeId: 'DSP-1003',
			status: 'accepted',
			evaluationType: 'qa',
			callId: 'CALL-2031',
			agentName: 'John Smith',
			scoreBefore: 71,
			scoreAfter: 82,
		},
	}),
	buildNotification({
		id: 'ntf-a10',
		agentId: AGENT_PERSONA_ID,
		category: 'POSITIVE_RECOGNITION',
		priority: 'LOW',
		title: 'You moved up to 3rd',
		message: 'September QA Sprint: you climbed one position this week.',
		icon: 'trophy',
		sourceRole: 'SYSTEM',
		read: true,
		createdAt: day(11, '06:00:00'),
		payload: {
			kind: 'RANKING_UPDATE',
			rankingId: 'RP-001',
			rankingName: 'September QA Sprint',
			event: 'POSITION_CHANGED',
			rank: 3,
			previousRank: 4,
			prizeTitle: '$100 gift card',
		},
	}),
	buildNotification({
		id: 'ntf-a11',
		agentId: AGENT_PERSONA_ID,
		category: 'DIRECT_MESSAGE',
		priority: 'NORMAL',
		title: 'Great save on the Ramirez call',
		message:
			'I listened to the Ramirez call this morning — the way you recovered the conversation after the pricing objection was exactly right. Can you walk the team through it on Friday?',
		icon: 'message',
		sourceRole: 'SUPERVISOR',
		sourceId: SUPERVISOR_PERSONA.id,
		createdAt: day(12, '10:05:00'),
		payload: { kind: 'MESSAGE' },
		replies: [
			{
				id: 'rep-001',
				fromRole: 'AGENT',
				fromId: AGENT_PERSONA_ID,
				message: 'Thanks Maria! Happy to. Should I prepare the recording?',
				createdAt: day(12, '10:30:00'),
			},
			{
				id: 'rep-002',
				fromRole: 'SUPERVISOR',
				fromId: SUPERVISOR_PERSONA.id,
				message: 'Yes please, just the last four minutes is enough.',
				createdAt: day(12, '11:02:00'),
			},
		],
	}),
	buildNotification({
		id: 'ntf-a12',
		agentId: AGENT_PERSONA_ID,
		category: 'DIRECT_MESSAGE',
		priority: 'NORMAL',
		title: 'Disclosure wording reminder',
		message:
			'Small thing: on two calls this week the rate disclosure came after the commitment. Please lead with it.',
		icon: 'message',
		sourceRole: 'QA_MANAGER',
		sourceId: QA_MANAGER_PERSONA.id,
		read: true,
		createdAt: day(7, '09:25:00'),
		payload: { kind: 'MESSAGE' },
	}),
	buildNotification({
		id: 'ntf-a13',
		agentId: AGENT_PERSONA_ID,
		category: 'METRIC_ALERT',
		priority: 'NORMAL',
		title: 'Compliance dipped on disclosures',
		message: 'Regulatory disclosure compliance is at 86%, under the 90% floor.',
		icon: 'shield',
		sourceRole: 'SYSTEM',
		metric: 'COMPLIANCE',
		read: true,
		createdAt: day(6, '08:00:00'),
		payload: {
			kind: 'METRIC_ALERT',
			area: 'COMPLIANCE',
			metricId: 'COMPLIANCE_REGULATORY_SCORE',
			value: 86,
			threshold: 90,
			direction: 'BELOW',
			windowLabel: 'Last 14 days',
			sparkline: [93, 92, 90, 89, 88, 87, 86],
			ruleName: 'Regulatory floor',
		},
		actions: [
			{
				label: 'Review the calls',
				url: '/qa/agent/calls?tab=calls&issue=compliance-regulatory&period=30d',
				icon: 'phone',
			},
		],
	}),
];

/** Maria García's inbox — her team's escalations. */
const SUPERVISOR_INBOX: AgentNotification[] = [
	buildNotification({
		id: 'ntf-s01',
		agentId: AGENT_PERSONA_ID,
		recipientRole: 'SUPERVISOR',
		recipientId: SUPERVISOR_PERSONA.id,
		category: 'DIRECT_MESSAGE',
		priority: 'HIGH',
		title: 'Dispute opened · David Brown',
		message: 'David disputes the compliance score of call CALL-2032.',
		icon: 'flag',
		sourceRole: 'AGENT',
		sourceId: 'AGT-006',
		createdAt: day(10, '16:05:00'),
		payload: {
			kind: 'DISPUTE_UPDATE',
			disputeId: 'DSP-1002',
			status: 'open',
			evaluationType: 'compliance',
			callId: 'CALL-2032',
			agentName: 'David Brown',
			scoreBefore: 78,
			scoreAfter: null,
		},
	}),
	buildNotification({
		id: 'ntf-s02',
		agentId: 'AGT-006',
		recipientRole: 'SUPERVISOR',
		recipientId: SUPERVISOR_PERSONA.id,
		category: 'TREND_WARNING',
		priority: 'CRITICAL',
		title: 'David Brown is at high burnout risk',
		message:
			'Four of the five burnout conditions are met. Consider adjusting his workload this week.',
		icon: 'flame',
		sourceRole: 'SYSTEM',
		createdAt: day(12, '07:10:00'),
		payload: {
			kind: 'BURNOUT_RISK',
			level: 'high',
			percentage: 78,
			drivers: ['negativeEmotionShare', 'ahtVsTeam', 'afterHoursShare'],
		},
	}),
	buildNotification({
		id: 'ntf-s03',
		agentId: SUPERVISOR_PERSONA.id,
		recipientRole: 'SUPERVISOR',
		recipientId: SUPERVISOR_PERSONA.id,
		category: 'METRIC_ALERT',
		priority: 'HIGH',
		title: 'Team compliance under the floor',
		message: 'Team 1 compliance is at 88%, below the 90% platform floor.',
		icon: 'shield',
		sourceRole: 'SYSTEM',
		metric: 'COMPLIANCE',
		createdAt: day(11, '08:00:00'),
		payload: {
			kind: 'METRIC_ALERT',
			area: 'COMPLIANCE',
			metricId: 'COMPLIANCE_OVERALL_SCORE',
			value: 88,
			threshold: 90,
			direction: 'BELOW',
			windowLabel: 'Last 30 days',
			sparkline: [93, 92, 91, 90, 89, 88, 88],
			ruleName: 'Team compliance floor',
		},
	}),
	buildNotification({
		id: 'ntf-s04',
		agentId: AGENT_PERSONA_ID,
		recipientRole: 'SUPERVISOR',
		recipientId: SUPERVISOR_PERSONA.id,
		category: 'DIRECT_MESSAGE',
		priority: 'NORMAL',
		title: 'Reply from John Smith',
		message: 'Thanks Maria! Happy to. Should I prepare the recording?',
		icon: 'message',
		sourceRole: 'AGENT',
		sourceId: AGENT_PERSONA_ID,
		threadId: 'ntf-a11',
		createdAt: day(12, '10:30:00'),
		payload: { kind: 'MESSAGE' },
	}),
	buildNotification({
		id: 'ntf-s05',
		agentId: SUPERVISOR_PERSONA.id,
		recipientRole: 'SUPERVISOR',
		recipientId: SUPERVISOR_PERSONA.id,
		category: 'WEEKLY_SUMMARY',
		priority: 'LOW',
		title: 'Team 1 week: 1–7 September',
		message: 'Seven agents evaluated, 299 calls, QA steady at 85%.',
		icon: 'calendar-stats',
		sourceRole: 'SYSTEM',
		read: true,
		createdAt: day(8, '07:00:00'),
		payload: {
			kind: 'WEEKLY_SUMMARY',
			weekLabel: '1–7 September',
			kpis: [
				{ label: 'QA score', value: '85%', delta: 1 },
				{ label: 'Compliance', value: '88%', delta: -2 },
				{ label: 'Sentiment', value: '3.9', delta: 0 },
				{ label: 'Calls', value: '299', delta: 12 },
			],
			highlights: [
				'Lisa Wong is the most improved agent this week.',
				'Two disputes are waiting on the QA Manager.',
			],
		},
	}),
	buildNotification({
		id: 'ntf-s06',
		agentId: SUPERVISOR_PERSONA.id,
		recipientRole: 'SUPERVISOR',
		recipientId: SUPERVISOR_PERSONA.id,
		category: 'POSITIVE_RECOGNITION',
		priority: 'NORMAL',
		title: 'August Sentiment Cup closed',
		message: 'Mike Chen finished first and earned the winner badge.',
		icon: 'trophy',
		sourceRole: 'SYSTEM',
		read: true,
		createdAt: day(1, '09:00:00'),
		payload: {
			kind: 'RANKING_UPDATE',
			rankingId: 'RP-003',
			rankingName: 'August Sentiment Cup',
			event: 'ENDED',
			prizeTitle: 'One extra day off',
		},
	}),
	buildNotification({
		id: 'ntf-s07',
		agentId: SUPERVISOR_PERSONA.id,
		recipientRole: 'SUPERVISOR',
		recipientId: SUPERVISOR_PERSONA.id,
		category: 'DIRECT_MESSAGE',
		priority: 'NORMAL',
		title: 'Follow-up overdue · Acme Retail',
		message: 'The callback promised to Laura Méndez was due two days ago.',
		icon: 'phone-call',
		sourceRole: 'SYSTEM',
		createdAt: day(12, '09:15:00'),
		payload: {
			kind: 'FOLLOW_UP',
			customerId: 'CUS-014',
			customerName: 'Laura Méndez',
			dueDate: '2026-09-10',
		},
	}),
];

/** Elena Ruiz's inbox — platform-wide items. */
const QA_MANAGER_INBOX: AgentNotification[] = [
	buildNotification({
		id: 'ntf-q01',
		agentId: AGENT_PERSONA_ID,
		recipientRole: 'QA_MANAGER',
		recipientId: QA_MANAGER_PERSONA.id,
		category: 'DIRECT_MESSAGE',
		priority: 'HIGH',
		title: 'Dispute opened · John Smith',
		message: 'John disputes the QA score of call CALL-2031.',
		icon: 'flag',
		sourceRole: 'AGENT',
		sourceId: AGENT_PERSONA_ID,
		createdAt: day(11, '09:20:00'),
		payload: {
			kind: 'DISPUTE_UPDATE',
			disputeId: 'DSP-1001',
			status: 'open',
			evaluationType: 'qa',
			callId: 'CALL-2031',
			agentName: 'John Smith',
			scoreBefore: 71,
			scoreAfter: null,
		},
	}),
	buildNotification({
		id: 'ntf-q02',
		agentId: 'AGT-015',
		recipientRole: 'QA_MANAGER',
		recipientId: QA_MANAGER_PERSONA.id,
		category: 'DIRECT_MESSAGE',
		priority: 'HIGH',
		title: 'Dispute opened · Camila Herrera',
		message: 'Camila disputes the sentiment evaluation of call CALL-2038.',
		icon: 'flag',
		sourceRole: 'AGENT',
		sourceId: 'AGT-015',
		createdAt: day(8, '14:00:00'),
		payload: {
			kind: 'DISPUTE_UPDATE',
			disputeId: 'DSP-1007',
			status: 'open',
			evaluationType: 'sentiment-emotion',
			callId: 'CALL-2038',
			agentName: 'Camila Herrera',
			scoreBefore: 2.5,
			scoreAfter: null,
		},
	}),
	buildNotification({
		id: 'ntf-q03',
		agentId: QA_MANAGER_PERSONA.id,
		recipientRole: 'QA_MANAGER',
		recipientId: QA_MANAGER_PERSONA.id,
		category: 'TREND_WARNING',
		priority: 'HIGH',
		title: 'Platform compliance is slipping',
		message:
			'Compliance fell from 93% to 89% across all teams over the last month, driven by Team 2.',
		icon: 'trending-down',
		sourceRole: 'SYSTEM',
		metric: 'COMPLIANCE',
		createdAt: day(12, '06:30:00'),
		payload: {
			kind: 'TREND_WARNING',
			area: 'COMPLIANCE',
			metricId: 'COMPLIANCE_OVERALL_SCORE',
			from: 93,
			to: 89,
			deltaPct: -4,
			periodLabel: 'Last 30 days',
			sparkline: [93, 93, 92, 91, 90, 90, 89],
			ruleName: 'Platform compliance trend',
		},
	}),
	buildNotification({
		id: 'ntf-q04',
		agentId: QA_MANAGER_PERSONA.id,
		recipientRole: 'QA_MANAGER',
		recipientId: QA_MANAGER_PERSONA.id,
		category: 'POSITIVE_RECOGNITION',
		priority: 'NORMAL',
		title: 'Compliance Champions Q3 started',
		message: 'The ranking is live for Team 2 and Team 3 until 30 September.',
		icon: 'trophy',
		sourceRole: 'SYSTEM',
		read: true,
		createdAt: day(2, '09:00:00'),
		payload: {
			kind: 'RANKING_UPDATE',
			rankingId: 'RP-002',
			rankingName: 'Compliance Champions Q3',
			event: 'STARTED',
			prizeTitle: 'Wall of fame + lunch with leadership',
		},
	}),
	buildNotification({
		id: 'ntf-q05',
		agentId: 'AGT-011',
		recipientRole: 'QA_MANAGER',
		recipientId: QA_MANAGER_PERSONA.id,
		category: 'POSITIVE_RECOGNITION',
		priority: 'LOW',
		title: 'Lucía Torres earned Compliance Guardian',
		message: 'Thirty consecutive calls without a compliance finding.',
		icon: 'award',
		sourceRole: 'SYSTEM',
		read: true,
		createdAt: day(6, '10:00:00'),
		payload: {
			kind: 'BADGE_EARNED',
			badgeId: 'BDG-004',
			badgeName: 'Compliance Guardian',
			badgeIcon: '🛡️',
			badgeColor: 'green',
			tier: 'GOLD',
			reason: 'Thirty consecutive calls with no compliance finding.',
		},
	}),
	buildNotification({
		id: 'ntf-q06',
		agentId: SUPERVISOR_PERSONA.id,
		recipientRole: 'QA_MANAGER',
		recipientId: QA_MANAGER_PERSONA.id,
		category: 'DIRECT_MESSAGE',
		priority: 'NORMAL',
		title: 'Question on the compliance rubric',
		message:
			'Elena, my team keeps losing points on the consent wording. Could we review the rubric wording together this week?',
		icon: 'message',
		sourceRole: 'SUPERVISOR',
		sourceId: SUPERVISOR_PERSONA.id,
		createdAt: day(12, '11:45:00'),
		payload: { kind: 'MESSAGE' },
	}),
];

/** Everything the notification store is seeded with, newest first. */
export const INBOX_SEED: AgentNotification[] = [
	...AGENT_INBOX,
	...SUPERVISOR_INBOX,
	...QA_MANAGER_INBOX,
].sort((a, b) => b.createdAt.localeCompare(a.createdAt));
