import type {
	DemoAgentCall,
	DemoAgentKpis,
	DemoCoachingReport,
	DemoLmsContent,
} from './types';

export const DEMO_AGENT_KPIS: DemoAgentKpis = {
	totalCampaigns: 3,
	weeklyPerformance: 82,
	avgCallScore: 78.5,
	totalCallsPerformed: 156,
	effectiveContactsCount: 142,
	nonEffectiveContactsCount: 14,
	monthlyTrends: [
		{ month: 'Jan', score: 72 },
		{ month: 'Feb', score: 75 },
		{ month: 'Mar', score: 78 },
		{ month: 'Apr', score: 76 },
		{ month: 'May', score: 81 },
		{ month: 'Jun', score: 79 },
		{ month: 'Jul', score: 83 },
		{ month: 'Aug', score: 85 },
		{ month: 'Sep', score: 82 },
		{ month: 'Oct', score: 80 },
		{ month: 'Nov', score: 84 },
		{ month: 'Dec', score: 82 },
	],
};

export const DEMO_AGENT_CALLS: DemoAgentCall[] = [
	{
		id: 'call-001',
		callDate: '2025-12-18T10:30:00Z',
		campaign: 'Q2 Sales Performance',
		duration: 420,
		score: 85,
		result: 'passed',
		disputed: false,
		evaluationType: 'QA',
		transcript: [
			{
				speaker: 'agent',
				text: 'Good morning! Thank you for calling. How can I assist you today?',
				timestamp: 0,
			},
			{
				speaker: 'customer',
				text: 'Hi, I have a question about my recent order.',
				timestamp: 3,
			},
			{
				speaker: 'agent',
				text: 'Of course! I\'d be happy to help. Can you provide your order number?',
				timestamp: 6,
			},
			{
				speaker: 'customer',
				text: 'Sure, it\'s ORD-123456.',
				timestamp: 9,
			},
			{
				speaker: 'agent',
				text: 'Perfect! Let me look that up for you.',
				timestamp: 12,
			},
		],
		evaluationDetails: [
			{
				section: 'Greeting & Opening',
				items: [
					{ name: 'Warm greeting', score: 5, maxPoints: 5 },
					{ name: 'Offered assistance', score: 5, maxPoints: 5 },
				],
			},
			{
				section: 'Customer Engagement',
				items: [
					{ name: 'Active listening', score: 4, maxPoints: 5 },
					{ name: 'Empathy demonstrated', score: 5, maxPoints: 5 },
				],
			},
		],
	},
	{
		id: 'call-002',
		callDate: '2025-12-17T14:15:00Z',
		campaign: 'Customer Support Quality',
		duration: 320,
		score: 72,
		result: 'failed',
		disputed: true,
		evaluationType: 'Compliance',
		transcript: [
			{
				speaker: 'agent',
				text: 'Support line, how can I help?',
				timestamp: 0,
			},
			{
				speaker: 'customer',
				text: 'My account is locked. I need help.',
				timestamp: 2,
			},
			{
				speaker: 'agent',
				text: 'Okay, let me help.',
				timestamp: 5,
			},
		],
		evaluationDetails: [
			{
				section: 'Compliance',
				items: [
					{ name: 'Data privacy notice', score: 0, maxPoints: 5 },
					{ name: 'Account verification', score: 3, maxPoints: 5 },
				],
			},
		],
	},
	{
		id: 'call-003',
		callDate: '2025-12-16T11:00:00Z',
		campaign: 'Q2 Sales Performance',
		duration: 480,
		score: 88,
		result: 'passed',
		disputed: false,
		evaluationType: 'Sentiment Analysis',
		transcript: [
			{
				speaker: 'agent',
				text: 'Hello! Great to hear from you. What can I help with?',
				timestamp: 0,
			},
			{
				speaker: 'customer',
				text: 'I\'d like to upgrade my plan.',
				timestamp: 3,
			},
			{
				speaker: 'agent',
				text: 'Excellent! I have some great options for you.',
				timestamp: 6,
			},
		],
		evaluationDetails: [
			{
				section: 'Sentiment',
				items: [
					{ name: 'Positive tone', score: 5, maxPoints: 5 },
					{ name: 'Customer satisfaction', score: 5, maxPoints: 5 },
				],
			},
		],
	},
	{
		id: 'call-004',
		callDate: '2025-12-15T09:45:00Z',
		campaign: 'New Hire Training – June',
		duration: 240,
		score: 65,
		result: 'failed',
		disputed: false,
		evaluationType: 'QA',
		transcript: [],
		evaluationDetails: [
			{
				section: 'Product Knowledge',
				items: [
					{ name: 'Accurate information', score: 3, maxPoints: 5 },
					{ name: 'Feature explanation', score: 2, maxPoints: 5 },
				],
			},
		],
	},
	{
		id: 'call-005',
		callDate: '2025-12-14T16:20:00Z',
		campaign: 'Customer Support Quality',
		duration: 360,
		score: 91,
		result: 'passed',
		disputed: false,
		evaluationType: 'QA',
		transcript: [],
		evaluationDetails: [
			{
				section: 'Problem Resolution',
				items: [
					{ name: 'Issue identified', score: 5, maxPoints: 5 },
					{ name: 'Solution provided', score: 5, maxPoints: 5 },
					{ name: 'Follow-up offered', score: 5, maxPoints: 5 },
				],
			},
		],
	},
	{
		id: 'call-006',
		callDate: '2025-12-13T13:30:00Z',
		campaign: 'Q2 Sales Performance',
		duration: 300,
		score: 79,
		result: 'passed',
		disputed: false,
		evaluationType: 'Compliance',
		transcript: [],
		evaluationDetails: [],
	},
	{
		id: 'call-007',
		callDate: '2025-12-12T10:00:00Z',
		campaign: 'Compliance Review – Q2',
		duration: 420,
		score: 87,
		result: 'passed',
		disputed: false,
		evaluationType: 'Compliance',
		transcript: [],
		evaluationDetails: [],
	},
	{
		id: 'call-008',
		callDate: '2025-12-11T15:45:00Z',
		campaign: 'Agent Performance Audit',
		duration: 340,
		score: 75,
		result: 'passed',
		disputed: false,
		evaluationType: 'QA',
		transcript: [],
		evaluationDetails: [],
	},
	{
		id: 'call-009',
		callDate: '2025-12-10T11:30:00Z',
		campaign: 'Customer Support Quality',
		duration: 280,
		score: 82,
		result: 'passed',
		disputed: false,
		evaluationType: 'Sentiment Analysis',
		transcript: [],
		evaluationDetails: [],
	},
	{
		id: 'call-010',
		callDate: '2025-12-09T14:00:00Z',
		campaign: 'Q2 Sales Performance',
		duration: 390,
		score: 84,
		result: 'passed',
		disputed: false,
		evaluationType: 'QA',
		transcript: [],
		evaluationDetails: [],
	},
];

export const DEMO_COACHING_REPORTS: DemoCoachingReport[] = [
	{
		id: 'report-001',
		campaign: 'Q2 Sales Performance',
		weekStart: '2025-12-15',
		weekEnd: '2025-12-19',
		performanceScore: 84,
		callsAnalyzed: 8,
		sections: {
			overview:
				'Strong performance this week with consistent quality across calls. You demonstrated excellent product knowledge and customer engagement skills.',
			metrics: {
				callsAnalyzed: 8,
				avgScore: 84,
				passRate: 87.5,
				trends: 'Up 5% from last week',
			},
			suggestions: [
				'Continue the positive momentum with customer engagement',
				'Work on reducing call duration while maintaining quality',
				'Explore upselling techniques in more conversations',
				'Focus on active listening in complex customer scenarios',
				'Review the one failed call for learning opportunities',
			],
			lmsReferences: [
				{ title: 'Active Listening Mastery', contentId: 'lms-001' },
				{ title: 'Upselling Best Practices', contentId: 'lms-002' },
			],
		},
	},
	{
		id: 'report-002',
		campaign: 'Customer Support Quality',
		weekStart: '2025-12-08',
		weekEnd: '2025-12-12',
		performanceScore: 79,
		callsAnalyzed: 6,
		sections: {
			overview:
				'Good progress this week. You handled most customer issues efficiently, with some areas for improvement in compliance documentation.',
			metrics: {
				callsAnalyzed: 6,
				avgScore: 79,
				passRate: 75,
				trends: 'Up 2% from previous week',
			},
			suggestions: [
				'Review compliance checklist before taking calls',
				'Ensure all required disclosures are mentioned',
				'Improve data verification procedures',
				'Great job on customer empathy',
				'Continue developing problem-solving skills',
			],
			lmsReferences: [
				{ title: 'Compliance & Regulations 101', contentId: 'lms-003' },
				{
					title: 'Customer Privacy & Data Protection',
					contentId: 'lms-004',
				},
			],
		},
	},
	{
		id: 'report-003',
		campaign: 'New Hire Training – June',
		weekStart: '2025-12-01',
		weekEnd: '2025-12-05',
		performanceScore: 71,
		callsAnalyzed: 5,
		sections: {
			overview:
				'You\'re making good progress as you continue your onboarding. Focus on strengthening product knowledge and building confidence.',
			metrics: {
				callsAnalyzed: 5,
				avgScore: 71,
				passRate: 60,
				trends: 'Up 4% from start of month',
			},
			suggestions: [
				'Complete product training module before next week',
				'Practice call scenarios with peer mentor',
				'Study competitor offerings for context',
				'Improve confidence in system navigation',
				'Schedule regular check-ins with supervisor',
			],
			lmsReferences: [
				{ title: 'Product Knowledge Bootcamp', contentId: 'lms-005' },
				{ title: 'System Navigation Guide', contentId: 'lms-006' },
				{
					title: 'Building Confidence in Customer Interactions',
					contentId: 'lms-007',
				},
			],
		},
	},
];

export const DEMO_LMS_CONTENTS: DemoLmsContent[] = [
	{
		id: 'lms-001',
		title: 'Active Listening Mastery',
		type: 'Video',
		mandatory: true,
		deadline: '2025-12-31',
		durationMin: 45,
		completed: true,
		completionPercent: 100,
	},
	{
		id: 'lms-002',
		title: 'Upselling Best Practices',
		type: 'Course',
		mandatory: false,
		durationMin: 90,
		completed: false,
		completionPercent: 0,
	},
	{
		id: 'lms-003',
		title: 'Compliance & Regulations 101',
		type: 'PDF',
		mandatory: true,
		deadline: '2025-12-25',
		durationMin: 30,
		completed: false,
		completionPercent: 40,
	},
	{
		id: 'lms-004',
		title: 'Customer Privacy & Data Protection',
		type: 'Video',
		mandatory: true,
		deadline: '2025-12-28',
		durationMin: 25,
		completed: false,
		completionPercent: 0,
	},
	{
		id: 'lms-005',
		title: 'Product Knowledge Bootcamp',
		type: 'Course',
		mandatory: true,
		deadline: '2025-12-31',
		durationMin: 180,
		completed: false,
		completionPercent: 60,
	},
	{
		id: 'lms-006',
		title: 'System Navigation Guide',
		type: 'PDF',
		mandatory: false,
		durationMin: 20,
		completed: true,
		completionPercent: 100,
	},
	{
		id: 'lms-007',
		title: 'Building Confidence in Customer Interactions',
		type: 'Article',
		mandatory: false,
		durationMin: 15,
		completed: false,
		completionPercent: 0,
	},
	{
		id: 'lms-008',
		title: 'Handling Difficult Customers',
		type: 'Video',
		mandatory: true,
		deadline: '2026-01-15',
		durationMin: 35,
		completed: false,
		completionPercent: 0,
	},
	{
		id: 'lms-009',
		title: 'Advanced Sales Techniques',
		type: 'Course',
		mandatory: false,
		durationMin: 120,
		completed: false,
		completionPercent: 25,
	},
	{
		id: 'lms-010',
		title: 'Communication Skills Workshop',
		type: 'Video',
		mandatory: false,
		durationMin: 50,
		completed: true,
		completionPercent: 100,
	},
];
