name: Deploy Frontend to S3 + CloudFront

on:
  push:
    branches: ["stable"]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: BPD

    steps:
      # 1. Checkout repo
      - name: Checkout Code
        uses: actions/checkout@v4

      # 2. Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"

      # 3. Install dependencies
      - name: Install dependencies
        run: pnpm install

      # 4. Build app
      - name: Build React App
        run: |
          export VITE_APP_API_URL=${{ secrets.API_URL }}
          pnpm run build # outputs dist/

      # 5. Configure AWS
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      # 6. Upload static assets (cache for 1 year)
      - name: Upload static assets
        run: |
          aws s3 sync ./dist s3://${{ secrets.S3_BUCKET_NAME }}/${{ secrets.FOLDER }} \
            --delete \
            --cache-control "max-age=31536000" \
            --exclude "index.html"

      # 7. Upload index.html without cache
      - name: Upload index.html
        run: |
          aws s3 cp ./dist/index.html s3://${{ secrets.S3_BUCKET_NAME }}/${{ secrets.FOLDER }}/index.html \
            --cache-control "no-cache"

      # 8. Upload extra folders (upload assets and images)
      - name: Upload extra folders
        run: |
          aws s3 sync ./assets s3://${{ secrets.S3_BUCKET_NAME }}/${{ secrets.FOLDER }}/assets \
            --delete \
            --cache-control "max-age=31536000"
          aws s3 sync ./images s3://${{ secrets.S3_BUCKET_NAME }}/${{ secrets.FOLDER }}/images \
            --delete \
            --cache-control "max-age=31536000"

      # 9. Invalidate CloudFront cache
      - name: Invalidate CloudFront cache
        run: |
          aws cloudfront create-invalidation \
            --distribution-id ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }} \
            --paths "/bpd-prod/*"
